- README.md
- src/index.ts
- Change `context` and `options` modifier from `private` to `protected` so they can be read in derived classes
- Allow initialization without schema or typeDefs/resolvers + error handling
- Moved `cors`, `bodyParser` and `apolloUpload` from `start` to constructor, so additional middlewares are added in the right place before `start` is called
- Renames backing property `schema` to `executableSchema` to avoid confusion because the `GraphQLSchema` type doesn't guarantee that the schema is actually executable. Also made it `protected` because it is not designed to be set manually for normal usage. This is technically a breaking change, but as I didn't change the constructor parameter `schema`, it should be okay.
> Changes to make `graphql-yoga` more extendable

- renovate.json
Updates `renovate.json` to add a rule to automerge any Renovate PR targeting `examples/*` directories. Adds an `examples-` prefix to the branchName to ensure that examples branches remain separate from the rest of the project.
Closes #61
> chore(renovate): automerge examples/* dependencies

- examples/file-upload/README.md
- examples/file-upload/index.ts
Some detailed examples can be added later, but this provides some useful clues about what we are looking at and how to get started.
Using curl with apollo-upload-server is especially tricky, so it might not actually be so useful.
> Improved Readme for file-upload example

- package.json
- yarn.lock
It doesn't seem to be used.  `graphql-tools` uses it, though.
> Remove `apollo-link`.

- src/index.ts
When checking across the graphql-yoga code because I had problems when setting up an apollo-server with Node.js, because the graphQL schema location was not properly set, I found this unuseful ternary operator.
> Code Cleaning: Update index.ts

- src/index.ts
There are two `apolloUploadExpress`  middlewares
> fix(Upload): remove duplicated apolloUploadExpress middleware

- package.json
- yarn.lock
`graphql-playground-middleware-lambda` complains if `aws-lambda` isn't around.  I don't think Lamda stuff should have been added here in the first place, but at the very least the user shouldn't be getting warnings.
> Fulfill `aws-lambda` peerDependency.

- src/index.ts
The signature of the Promise returned from `start` expects a `Server`, but one is not returned from the case where there is no subscription.
> Resolve promise with server in non-subscription case

- src/index.ts
- src/lambda.ts
- src/types.ts
This PR fixes: https://github.com/graphcool/graphql-yoga/issues/185.
Adopt `ITypeDefinitions` from `graphql-tools` for typeDefs type.
Type check before trying to verify if typeDefs is a string containing a path to import `graphql.schema`
> feat: suport array syntax for typeDefs argument

- README.md
- src/index.ts
- src/types.ts
I need access to onConnect for verifying the access token on a websocket connection.  Then I need access to onDisconnect to perform some clean up when a websocket disconnects.
> Expose subscription server onConnect and onDisconnect options

- README.md
- package.json
- prettier.config.js
- src/index.ts
- src/lambda.ts
- src/types.ts
- yarn.lock
In response to https://www.apollographql.com/docs/graphql-tools/schema-directives.html
Closes #218, #208 
Other improvements:
* __update dependencies__
*  __switch to local instance of prettier and prettier config__
The repo has two new dependencies (`prettier` and `prettier-check`), which allow for checking code formatting as a part of linting and also make it possible to format source files from an npm script. This can be useful for those who's text editor is not properly configured. With `prettier.config.js` becoming a part of this repo, there's no confusion about what prettier options to use. The workflow is now similar to what [`apollo-server`](https://github.com/apollographql/apollo-server) uses.
When I started editing `ts` files initially, even a tiny tweak produced a huge diff …
> Support schema directives

- README.md
- src/index.ts
Adding possibility for multiple files in `typedefs` fixes #205. Documentation needs to be updated, because its missing support for arrays in general :)
> Adding possibility for multiple files in typedefs

- README.md
I mistakenly didn't include this on PR #237.
> docs(readme): Mention port can be a string

- examples/modular-resolvers/README.md
- examples/modular-resolvers/data/data.ts
- examples/modular-resolvers/index.ts
- examples/modular-resolvers/package.json
- examples/modular-resolvers/resolvers/index.ts
- examples/modular-resolvers/resolvers/user.resolvers.ts
- examples/modular-resolvers/resolvers/welcome.resolvers.ts
- examples/modular-resolvers/tsconfig.json
- examples/modular-resolvers/typeDefs/index.ts
- examples/modular-resolvers/typeDefs/user.typedefs.graphql
- examples/modular-resolvers/typeDefs/welcome.typedefs.graphql
This example illustrates how one could organize typeDef and resolver files in any manner and merge them using `merge-graphql-schemas`. 
Closes #136 
Closes #214
> Example that illustrates modular typeDef and resolvers file organization

- src/customFieldResolver.ts
- src/index.ts
- src/lambda.ts
Use an alias aware field resolver as a default if a custom resolver is not supplied. This is required to get around https://github.com/graphcool/prisma/issues/1896
Please let me know if any changes are needed.
> Use an alias aware field resolver as a default

- README.md
- src/index.ts
This pull request passes the express response object as a parameter to the context when it is a function.
1. Setting up cookie.
2. Sending a custom response.
3. Authentication and Session Management.
> Add Response to context as well.

- examples/apollo-engine/index.js
- examples/apollo-engine/package.json
- src/index.ts
- src/types.ts
Related: #206 
Just for sharing and discussing.
TODO:
BTW, it can be nice to add a prettier in this project, my VSCode reformat everything without my permission…
Please note that you need to `npm link` or `yarn link` with the local version of `graphql-yoga` to try 😉 (it can be obvious, but just in case ^^)
> Upgrade apollo-engine to 1.0.1

- examples/query-complexity/README.md
- examples/query-complexity/index.js
- examples/query-complexity/package.json
- src/index.ts
- src/lambda.ts
- src/types.ts
I started playing with implementing complexity analysis and noticed I couldn't use yoga + the library I wanted ([graphql-cost-analysis](https://github.com/pa-bru/graphql-cost-analysis)).
Added example with measuring query complexity + did the required change in yoga to support it.
👯‍♂️  **Non-breaking change** 👯‍♂️
> `validationRules` as callback + query complexity example

- src/index.ts
> fix(server): make `start` method callback receive correct port info

- src/index.test.ts
Now that the package is adding tests, here is a new test for [graphql-deduplicator](graphql-deduplicator), in this test the `data` is checked to be deduplicated if the client wants it.
I can also create a new test case for when the `deduplicator` option is set as `false`, in such case the response should never be deduplicated, if you think it's required let me know!
> Added new tests for graphql-deduplicator

- src/lambda.ts
`sls offline` plugin throws a warning when a lambda handler function returns a promise and calls the callback. This PR fixes that.
> fix: warning generated by sls offline about promise, callback

- package.json
- src/index.ts
- src/types.ts
- yarn.lock
`yarn test` still yields the following error in middleware types. 
```
src/types.ts(125,17): error TS2315: Type 'IMiddleware' is not generic.
```
> fix: potential incorrect merge conflict resolution

- src/lambda.ts
- src/types.ts
Fixes #313 (https://github.com/prismagraphql/prisma/issues/2225)  for `GraphQLServerLambda`, this was fixed for `GraphQLServer` in pull request #270
> Support `resolverValidationOptions` in lambda

- src/lambda.ts
- src/types.ts
Closes #398 wrapping `executableSchema` with `applyMiddleware` from [graphql-middleware](https://github.com/prismagraphql/graphql-middleware)
> Add middlewares to GraphQLServerLambda

- package.json
Not sure if leaving it out was intentional, but it doesn't display nicely in npm:
> Adding description to package.json

- src/types.ts
The docs specify `mocks` can be a list of mocks or `true`, and the code bears this out, but the types only allow `IMocks` or nothing.
> Types don't match docs & usage

- examples/modular-resolvers/index.ts
- examples/modular-resolvers/resolvers/index.ts
- src/index.test.ts
- src/index.ts
- src/types.ts
this is already supported by `makeExecutableSchema`, so no additional implementation was necessary.
I've also updated the associated example accordingly
> allow resolvers to be an array of resolvers

- src/types.ts
the IResolvers type from graphql-tools is generic, and allows specifying the type of the source and the context.
Since these were previously exported, we might want to re-export them until a major version bump happens, to prevent apps from breaking.
> import IResolvers from graphql-tools for better types

- src/types.ts
Lambda context isn't called with the same parameters as the express version:
https://github.com/prismagraphql/graphql-yoga/blob/e73f9b68a405e43d5260c8068b3d3244a4d00730/src/lambda.ts#L116
vs
https://github.com/prismagraphql/graphql-yoga/blob/e73f9b68a405e43d5260c8068b3d3244a4d00730/src/index.ts#L254
> fix: Update lambda type signatures

- README.md
As the title indicates, this updates “middlewares” to “middleware”, which is the correct pluralization of the word ([reference](https://english.stackexchange.com/questions/257120/middleware-vs-middlewares)). 
Unfortunately it looks like “middlewares” is also used as a configuration option in a few places that get exposed to the user, so I left those.
> Correct plural form of “middleware”

- package.json
This package currently depends on aws-lambda, which depends on aws-sdk, which is a _massive_ package (41MB, before dependencies).
This is only used in [`types.ts`](https://github.com/prisma/graphql-yoga/blob/master/src/types.ts), which uses it only for type definitions. These don't exist at runtime (check out the empty compiled version in [`types.js`](https://unpkg.com/graphql-yoga@1.18.0/dist/types.js)), and aws-lambda is never actually used directly.
Unfortunately, aws-lambda is a production dependency of this package, and @types/aws-lambda is a development dependency, which means:
* Every user of this package has to download aws-lambda & aws-sdk, and deploy it as part of their codebase (discussed in #436, but never fixed).
* Every TypeScript user of this package has to manually install …
> Fix AWS dependencies - shrinks this package by 60%

- packages/graphql-yoga/__tests__/integration.spec.ts
- packages/graphql-yoga/package.json
- packages/graphql-yoga/src/index.ts
- packages/graphql-yoga/src/types.ts
- packages/graphql-yoga/test-utils/schema.ts
- yarn.lock
Not sure about W3 Response there but W3 Response there might be future proof for `defer/stream` and subscriptions. Also a flag for `multipart` might be good in case of file upload/multipart request
> Use File interface in resolvers, Blob as scalar name and Response as a return type of inject

- examples/subscriptions/README.md
- examples/subscriptions/src/index.ts
- packages/graphql-yoga/package.json
- packages/graphql-yoga/src/events.d.ts
- packages/graphql-yoga/src/pubsub.ts
- website/docs/quick-start.mdx
- yarn.lock
Event and EventTarget are not available as globals within Node.js 14, but starting Node.js 16.
```ts
import EventTarget from '@ungap/event-target'
import Event from '@ungap/event'
```
> cross platform events

- packages/graphql-yoga/__tests__/integration.spec.ts
- packages/handler/src/getResponse.ts
- packages/handler/src/processRequest.ts
closes and adds tests for https://github.com/dotansimha/graphql-yoga/issues/739 + remove stack traces from the outside world
> context error handling

- .changeset/funny-flies-boil.md
- packages/node/package.json
- packages/subscription/package.json
- packages/subscription/src/createPubSub.spec.ts
- packages/subscription/src/createPubSub.ts
- yarn.lock
The following was broken.
```typescript
const pubSub = createPubSub<{
a: [id: string, payload: number]
}>()
const id1 = '1'
const sub1 = pubSub.subscribe('a', id1)
const allValues1 = collectAsyncIterableValues(sub1)
pubSub.publish('a', id1, 1)
pubSub.publish('a', id1, 2)
pubSub.publish('a', id1, 3)
setImmediate(() => {
sub1.return()
})
const result1 = await allValues1
expect(result1).toEqual([1, 2, 3])
```
I added a test suite for the `createPubSub`.
Also I replaced the `@ungap/event` and `@ungap/event-target` polyfill recommendations with `event-target-polyfill` as the former dd only work in browser environments.
> fix: scoped resource subscriptions

- .changeset/cool-ads-divide.md
- packages/node/src/http-utils.ts
> fix(node): remove port identifier from host header if used as hostname to build Request

- .changeset/thick-cooks-run.md
- packages/node/src/http-utils.ts
- packages/node/src/index.ts
Needed to block the promise for the server frameworks that are relying on promise resolution like Express's AsyncRouter and Serverless Express
> fix(node): resolve sendNodeResponse correctly when stream has been finished

- .changeset/clever-mugs-hug.md
- .changeset/two-knives-behave.md
- examples/nextjs-auth/pages/api/graphql.ts
- packages/common/src/getResponse.ts
- packages/node/__tests__/integration.spec.ts
According to GraphQL over HTTP spec, even if there is `errors`, we should still return `data: null`, and content-type should be `application/json`.
https://github.com/graphql/graphql-over-http/blob/main/spec/GraphQLOverHTTP.md#status-codes
> Add missing content-type and data property for error responses

- packages/common/src/server.ts
Error masking from yoga should always happen last, as we don't want users using the sentry envelop plugin or other plugins that hook into onExecute to receive the already masked errors.
> fix: apply masked errors last

- website/src/google-analytics.ts
- website/src/pages/_app.tsx
> Why not a component? Next.js + CJS goes crazy when I use `next/router.js` and `next/script.js`.
> I get: https://reactjs.org/docs/error-decoder.html/?invariant=130&args%5B%5D=object&args%5B%5D=
> Probably because of two different versions of React or something. Not sure...
I could do a component here, just for Yoga website but keeping it the same as in `@guild-docs/client` makes it easier to transition later.
Other Guild websites imports `useGoogleAnalytics` hook from `@guild-docs/client` but it does not currently work with React 18 (Yoga uses 18).
> Use Google Analytics

- website/docs/features/context.mdx
- website/routes.ts
I think most people don't care about server context really and only want to quickly learn how `context: () => brrt` works.
So I tried restructuring it, the most important info for people that wanna get started is now on top, the advanced stuff and details are below.
> docs: revamp context documentation

- .github/workflows/ci.yml
- .vscode/settings.json
- examples/netlify-edge/.netlify/edge-functions-import-map.json
- examples/netlify-edge/.netlify/state.json
- examples/netlify-edge/index.html
- examples/netlify-edge/netlify.toml
- examples/netlify-edge/netlify/edge-functions/graphql.ts
- examples/netlify-edge/package.json
- yarn.lock
Closes https://github.com/dotansimha/graphql-yoga/issues/1107
> Add Netlify Edge example

- .changeset/empty-readers-kick.md
- packages/common/src/server.ts
- packages/node/__tests__/integration.spec.ts
> Send specific origin in CORS instead of wildcard if credentials are allowed explicitly

- website/tutorial/basic/08-graph-relations.mdx
fix the typos mentioned in https://github.com/dotansimha/graphql-yoga/discussions/1167#discussioncomment-2691924
> docs: fix typos

- website/docs/integrations/integration-with-fastify.mdx
The docs specify the key to be logger but I got this
It should be `logging` rather if I am not wrong
> Fix docs - replace logger with logging

- .changeset/grumpy-comics-yell.md
- packages/common/src/processRequest.ts
- packages/common/src/server.ts
- packages/node/__tests__/integration.spec.ts
Fix GraphQLYogaError being thrown from within the`contextFactory` to be treated as an unexpected error.
The bug would previously prevent the GraphQLYogaError `extensions` from being exposed in the result and cause a status code of 500.
> fix: correctly handle GraphQLYogaError thrown in contextFactory

- .changeset/sweet-bags-swim.md
- packages/common/scripts/generate-graphiql-html.js
- packages/common/src/graphiql.html
- packages/common/src/plugins/useGraphiQL.ts
- scripts/canary-release.js
The GraphiQL version that is loaded from CDN should be consistent for a single version so that the GraphiQL does not unexpectedly break in the future when its API is changed and this newer version is loaded from the CDN. 
This PR changes the HTML build script to include the proper version string.
> feat: scope GraphiQL to version compatible with common

- scripts/vercel-ignore-build-step.sh
Apply changes mentioned in https://github.com/dotansimha/graphql-yoga/issues/1264#issuecomment-1146820656
> We originally introduced that script in order to reduce noise and a clogged-up vercel build queue for all the PRs created by renovate. However, as we are now batching renovate updates into less frequent PRs it should be fine to run vercel builds/deployments on every PR.
By running this on every PR we have a higher chance of catching dependency updates that break vercel deployments.
> chore: run vercel builds on renovate pull requests

- .changeset/fast-shirts-join.md
- examples/fastify/package.json
- examples/fastify/src/app.ts
- examples/fastify/src/index.ts
- examples/sveltekit/__tests__/test.ts
- packages/common/__tests__/logging.test.ts
- packages/common/src/logger.ts
- packages/common/src/server.ts
- packages/node/src/index.ts
- website/docs/integrations/integration-with-fastify.mdx
- yarn.lock
Previously sometimes Yoga used to send data to the provided logger like below;
```js
yogaLogger.debug(arg1, arg2, arg3)
```
This behavior is working fine with JavaScript's native `console` implementation but most of the other non native logger implementation like Pino only accept a single parameter for its logging methods. So we decided to avoid sending multiple parameters to the logger.
However, in order to prevent a breaking change, we kept the signatures of logger methods and they will still accept multiple parameters in a single call. You should keep on mind that eventually we will stop accepting multiple parameters and have the behavior similar to Pino's.
We still recommend to update your `logging` parameter in `createServer` call to make sure the other parameters after the first one …
> Logging refactor

- packages/common/package.json
- packages/common/scripts/generate-graphiql-html.js
- yarn.lock
The library using native bindings caused issues on vercel. By using a pure JavaScript library we work around these issues.
____
Closes https://github.com/dotansimha/graphql-yoga/issues/1301
> chore: use pure js library for minifying html

- .changeset/fast-shirts-join.md
https://github.com/dotansimha/graphql-yoga/pull/1292 introduced a changeset that broke the builds, due to a missing version bump header.
I added these a patch changes, but it is open for discussion whether this is actually a major (breaking) change...
> chore: fix the invalid changeset added within #1292

- .changeset/shy-geckos-switch.md
- examples/graphql-config/package.json
- examples/subscriptions/package.json
- examples/sveltekit/__tests__/test.ts
- package.json
- packages/common/src/GraphQLYogaError.ts
- packages/common/src/plugins/requestParser/POSTMultipart.ts
- packages/common/src/plugins/types.ts
- packages/common/src/plugins/useCORS.ts
- packages/common/src/plugins/useGraphiQL.ts
- packages/common/src/plugins/useHealthCheck.ts
- packages/common/src/processRequest.ts
- packages/common/src/server.ts
- packages/common/src/types.ts
- packages/node/__tests__/integration.spec.ts
- yarn.lock
- Remove the unnecessary generics from Yoga hooks
- Simplify error handling code. So we introduce a new extension field `http` that lets user to decide the HTTP status code and headers. This is still experimental. I think we can document it later.
- Handle Multipart Limit errors correctly and return 413 ( Request Entity Too Large ) HTTP status code in that case.
Closes https://github.com/dotansimha/graphql-yoga/issues/1324
> Refactor Error Handling & Return correct HTTP status codes for Multipart

- website/docs/features/envelop-plugins.mdx
Fixing a small typo in the envelop example.
> docs(envelop): fix typo in envelop example

- examples/nextjs-auth/pages/api/graphql.ts
- examples/nextjs/pages/api/graphql.ts
- packages/node/__tests__/integration.spec.ts
- website/docs/integrations/integration-with-nextjs.mdx
Trying to reproduce https://github.com/dotansimha/graphql-yoga/issues/1331 with `@graphql-yoga/node` in standalone mode. It seems like file uploads only get corrupted with Next.js, which I reproduced locally (See https://github.com/n1ru4l/next-js-yoga-file-upload-reproduction#readme).
______
Closes https://github.com/dotansimha/graphql-yoga/issues/1331
> add test to ensure yoga does not corrupt uploaded files + update Next.js examples/instructions

- packages/common/src/plugins/requestValidation/useCheckGraphQLQueryParam.ts
- packages/common/src/plugins/requestValidation/useCheckMethodForGraphQL.ts
- packages/common/src/plugins/requestValidation/useHTTPValidationError.ts
- packages/common/src/plugins/requestValidation/usePreventMutationViaGET.ts
- packages/common/src/processRequest.ts
- packages/common/src/server.ts
Motivation;
This PR moves all the business logic done for covering the spec from `processRequest` to individual plugins by using Envelop and Yoga's hooks. 
So we can see the default request/execution flow is now more clear because all those null checks etc looks a bit messy even if we try to keep them clean in that `processRequest` function.
It is more clear that we get the request object first, then extract GraphQL params with the specific request processor. After that, we parse the query parameter then validate it etc etc.
See here;
https://github.com/dotansimha/graphql-yoga/blob/6a20a3183f340922b9975b9785837dda72e7c832/packages/common/src/processRequest.ts#L18
Possible next tasks;
- Later we can categorize tests by the plugin to make it easier to find, maintain and update in the long …
> Refactor request processing

- .changeset/lazy-countries-unite.md
- .changeset/new-lobsters-scream.md
- .changeset/silly-lions-rest.md
- examples/redis-pub-sub/README.md
- examples/redis-pub-sub/package.json
- examples/redis-pub-sub/src/main.ts
- examples/redis-pub-sub/tsconfig.json
- examples/sveltekit/__tests__/test.ts
- package.json
- packages/event-target/redis-event-target/README.md
- packages/event-target/redis-event-target/__tests__/redis-event-target.spec.ts
- packages/event-target/redis-event-target/package.json
- packages/event-target/redis-event-target/src/index.ts
- packages/event-target/typed-event-target/README.md
- packages/event-target/typed-event-target/package.json
- packages/event-target/typed-event-target/src/index.ts
- packages/subscription/package.json
- packages/subscription/src/createPubSub.spec.ts
- packages/subscription/src/createPubSub.ts
- patches/@types+ioredis-mock+5.6.0.patch
- tsconfig.json
- website/docs/features/subscriptions.mdx
- yarn.lock
- This moves the `TypedEventTarget` type into a standalon package `@graphql-yoga/typed-event-target`.
- Adds the `@graphql-yoga/redis-event-target` package which has a EventTarget implementation based on redis pub/sub using `ioredis`
Future thoughts:
- I used Event with a custom `data` attribute, and now I figured out that there is also [`CustomEvent`](https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent), but it is still not available in the latest Node.js. Changing the API to use `CustomEvent` would be a breaking change, thus for now I kept re-using the `Event`. In the next major release, we can consider using `CustomEvent` instead.
_____
Node.js Progress for supporting `CustomEvent`:
- https://github.com/nodejs/node/issues/40678
- https://github.com/nodejs/node/pull/43514 …
> feat: RedisEventTarget

- .github/workflows/algolia-integrity.yml
- .github/workflows/algolia-publish.yml
- .github/workflows/benchmark.yml
- .github/workflows/ci.yml
- .github/workflows/deployment-e2e.yml
- .github/workflows/release.yml
- .github/workflows/website-integrity.yml
applying patch-package patches is skipped as `node_modules` are cached without the patches being part of the cache key. By including them within the cache key we ensure that fresh node_modules are installed (and the patches are applied).
> chore: include patches in hash

- .changeset/unlucky-bobcats-cheer.md
- .github/workflows/ci.yml
- examples/error-handling/package.json
- package.json
- packages/common/package.json
- packages/node/__tests__/integration.spec.ts
- packages/node/package.json
- packages/node/src/http-utils.ts
- yarn.lock
AsyncIterables returned from the `subscribe/execute` functions are not cleaned up (the `return` function is not called).
This causes memory leaks which results in the server going out of memory and crashing.
I created an integration test that proves a subscription is not cleaned up. 
It seems like the underlying issue might be within cross-undici-fetch but I am not 100% sure what is going wrong here.
________
Runnable example on CodeSandbox over here: https://codesandbox.io/s/regression-subscription-not-closed-d8d5mj?file=/index.ts
> fix: incremental delivery and subscription source cleanup

- website/docs/features/context.mdx
Link went to `features/envelop-plugins` instead of `docs/features/envelop-plugins`, meaning you got a 404 :)
> docs: fixed broken link to envelop plugins

- .changeset/bright-wasps-boil.md
- .github/workflows/ci.yml
- tsconfig.json
PR of #1349 
________
Closes #1349
> Remove node 12 Support

- .changeset/hungry-knives-raise.md
- .changeset/pretty-cycles-wait.md
- examples/sveltekit/__tests__/test.ts
- packages/apollo-link/package.json
- packages/apollo-link/src/index.ts
- packages/apollo-link/test/apollo-link.test.ts
- packages/urql-exchange/package.json
- packages/urql-exchange/src/index.ts
- packages/urql-exchange/test/urql-exchange.test.ts
- tsconfig.json
- website/v3/docs/features/subscriptions.mdx
- yarn.lock
Closes https://github.com/dotansimha/graphql-yoga/issues/1381
Closes https://github.com/dotansimha/graphql-yoga/issues/1380
> Urql Exchange & Apollo Client Link

- .changeset/chilly-rats-marry.md
- .changeset/twenty-poets-prove.md
- packages/graphql-yoga/src/plugins/types.ts
- packages/graphql-yoga/src/plugins/useResultProcessor.ts
- packages/graphql-yoga/src/processRequest.ts
- packages/graphql-yoga/src/server.ts
- packages/graphql-yoga/src/types.ts
- packages/plugins/response-cache/README.md
- packages/plugins/response-cache/__tests__/response-cache.spec.ts
- packages/plugins/response-cache/package.json
- packages/plugins/response-cache/src/index.ts
- website/routes.ts
- website/v3/docs/features/response-caching.mdx
- yarn.lock
See the changesets
https://github.com/dotansimha/graphql-yoga/pull/1359/files
I am open for discussions about passing `params` and `request` instead of `context` in `sessionId` factory. 
We need some unit tests for the new `sessionId` factory and to make sure `execute`, `validate` or even `parse` are never called before this plugin returns the cached response.
Need docs
> Response Cache plugin with small changes for better type-safety

- .changeset/more-accept-headers.md
- e2e/utils.ts
- packages/graphql-yoga/__tests__/node.spec.ts
- packages/graphql-yoga/src/plugins/resultProcessor/multipart.ts
- packages/graphql-yoga/src/plugins/resultProcessor/push.ts
- packages/graphql-yoga/src/plugins/resultProcessor/regular.ts
- packages/graphql-yoga/src/plugins/types.ts
- packages/graphql-yoga/src/plugins/useResultProcessor.ts
- packages/graphql-yoga/src/processRequest.ts
- packages/graphql-yoga/src/server.ts
Related #https://github.com/dotansimha/graphql-yoga/pull/1503#issue-1322023154
Closes #1504
Currently Yoga processes only async iterable results according to the accept header, but instead we should respect the header even for regular results. So async iterable check should be done only for json responses.
> Respect Accept headers in a more strict way

- website/docs/features/subscriptions.mdx
There is an error with import. 
```
'Redis' cannot be used as a value because it was exported using 'export type'.ts(1362)
```
Take a look here https://github.com/luin/ioredis
> docs: Fix bad redis import

- .changeset/grumpy-pens-watch.md
- packages/common/src/server.ts
- packages/node/__tests__/integration.spec.ts
Apply the HTTP validation error plugin last in order to not interfere error masking when using the `handleValidationErrors` option.
______
originally reported by @dthyresson on Slack
> fix: apply the useHTTPValidationError plugin last

- .changeset/cool-dots-notice.md
- examples/apollo-federation/gateway/package.json
- examples/fastify-modules/package.json
- examples/generic-auth/package.json
- examples/live-query/package.json
- examples/sveltekit/package.json
- packages/common/package.json
- packages/node/__tests__/integration.spec.ts
- packages/node/package.json
- yarn.lock
Upgrades envelop and adds a test for ensuring that the error is exposed as the `extensions.originalError` in dev mode.
_________
Closes https://github.com/dotansimha/graphql-yoga/issues/1585
Related:
- https://github.com/dotansimha/graphql-yoga/issues/1585
- https://github.com/dotansimha/graphql-yoga/issues/1584
> fix: upgrade envelop

- .changeset/grumpy-kangaroos-tell.md
- .changeset/seven-tomatoes-invent.md
- examples/graphql-ws/__integration-tests__/graphql-ws.spec.ts
- examples/graphql-ws/src/app.ts
- examples/graphql-ws/src/index.ts
- packages/graphql-yoga/src/plugins/requestValidation/usePreventMutationViaGET.ts
- packages/graphql-yoga/src/server.ts
- website/docs/features/subscriptions.mdx
Closes #1513
I was considering checking the headers and skipping the check if `Upgrade: websocket`; however, the `request` in the context is a Node request... @ardatan suggestions? Use `normalizeNodeRequest from @whatwg-node/server`? Include `socket` in context and skip check if `socket` is set (this would require WebSocket type)?
P.S. the test is not failing on `v3-graphql-http` branch because I dropped the plugin and left the check to graphql-http.
> graphql-ws integration adjustments and tests (V3)

- .vscode/extensions.json
- .vscode/settings.json
- `search.useGlobalIgnoreFiles` instead of list
- `files.exclude` is mostly defaults, I want all of it in the explorer
- `deno.enable` is unnecessary with `deno.enablePaths`
- `deno.unstable` should be users choice
- dropped `eslint.format.enable`, formatting will be done by prettier instead
- correct sdk paths
- formatting timing is users choice
> Unopinionated vscode settings

- .changeset/tall-paws-do.md
- packages/graphql-yoga/__tests__/accept-header.spec.ts
- packages/graphql-yoga/src/plugins/resultProcessor/regular.ts
Also now the order is updated per spec.
> Support 'application/graphql-response+json'

- .changeset/fuzzy-plums-check.md
- examples/deno/index.ts
- packages/common/src/server.ts
- website/src/pages/docs/integrations/integration-with-deno.mdx
The Deno example does not work against the latest version of `graphql-yoga` or `Deno`.
This PR fixes and upgrades the version of `serve`.
> upgrade and fix Deno example

- packages/graphql-yoga/src/plugins/types.ts
- packages/graphql-yoga/src/plugins/useGraphiQL.ts
- packages/graphql-yoga/src/plugins/useHealthCheck.ts
- packages/graphql-yoga/src/plugins/useUnhandledRoute.ts
- packages/graphql-yoga/src/server.ts
closes https://github.com/dotansimha/graphql-yoga/issues/1486
> refactor: create `URL` instance once and pass it in context for `onRequestHook`

- .changeset/nine-brooms-cough.md
- examples/graphql-ws/src/app.ts
- packages/graphql-yoga/__tests__/batching.spec.ts
- packages/graphql-yoga/src/plugins/requestParser/POSTJson.ts
- packages/graphql-yoga/src/plugins/requestParser/POSTMultipart.ts
- packages/graphql-yoga/src/plugins/requestValidation/useCheckGraphQLQueryParams.ts
- packages/graphql-yoga/src/plugins/requestValidation/useLimitBatching.ts
- packages/graphql-yoga/src/plugins/requestValidation/usePreventMutationViaGET.ts
- packages/graphql-yoga/src/plugins/resultProcessor/multipart.ts
- packages/graphql-yoga/src/plugins/resultProcessor/push.ts
- packages/graphql-yoga/src/plugins/resultProcessor/stringify.ts
- packages/graphql-yoga/src/plugins/types.ts
- packages/graphql-yoga/src/plugins/useRequestParser.ts
- packages/graphql-yoga/src/processRequest.ts
- packages/graphql-yoga/src/server.ts
- packages/graphql-yoga/src/types.ts
- packages/plugins/apollo-inline-trace/src/index.ts
- packages/plugins/apq/src/index.ts
- packages/plugins/persisted-operations/src/index.ts
- packages/plugins/response-cache/src/index.ts
Closes https://github.com/dotansimha/graphql-yoga/issues/1661
> Batching RFC support

- examples/file-upload/__integration-tests__/file-upload.spec.ts
- examples/file-upload/index.ts
- examples/file-upload/yoga.ts
> test: file-upload example

- examples/file-upload-nexus/__integration-tests__/file-upload-nexus.spec.ts
- examples/file-upload-nexus/index.ts
- examples/file-upload-nexus/yoga.ts
> test: file-upload-nexus example

- .changeset/@graphql-yoga_redis-event-target-1761-dependencies.md
- .changeset/@graphql-yoga_subscription-1761-dependencies.md
- .changeset/sour-apricots-move.md
- packages/event-target/redis-event-target/__tests__/redis-event-target.spec.ts
- packages/event-target/redis-event-target/package.json
- packages/event-target/redis-event-target/src/index.ts
- packages/event-target/typed-event-target/src/index.ts
- packages/subscription/package.json
- packages/subscription/src/createPubSub.ts
- website/src/pages/v3/features/subscriptions.mdx
- yarn.lock
> Use CustomEvent for PubSub and TypedEventTarget impl

- website/src/pages/v3/_meta.json
- website/src/pages/v3/comparison.mdx
- website/src/pages/v3/features/automatic-persisted-queries.mdx
- website/src/pages/v3/features/cors.mdx
- website/src/pages/v3/features/envelop-plugins.mdx
- website/src/pages/v3/features/error-masking.mdx
- website/src/pages/v3/features/file-uploads.mdx
- website/src/pages/v3/features/graphiql.mdx
- website/src/pages/v3/features/persisted-operations.mdx
- website/src/pages/v3/features/response-caching.mdx
- website/src/pages/v3/features/subscriptions.mdx
- website/src/pages/v3/features/testing.mdx
- website/src/pages/v3/index.mdx
- website/src/pages/v3/integrations/integration-with-aws-lambda.mdx
- website/src/pages/v3/integrations/integration-with-cloudflare-workers.mdx
- website/src/pages/v3/integrations/integration-with-deno.mdx
- website/src/pages/v3/integrations/integration-with-express.mdx
- website/src/pages/v3/integrations/integration-with-fastify.mdx
- website/src/pages/v3/integrations/integration-with-koa.mdx
- website/src/pages/v3/integrations/integration-with-nestjs.mdx
- website/src/pages/v3/integrations/integration-with-nextjs.mdx
- website/src/pages/v3/integrations/integration-with-sveltekit.mdx
- website/src/pages/v3/integrations/z-other-environments.mdx
- website/src/pages/v3/migration/_meta.json
- website/src/pages/v3/migration/migration-from-apollo-server.mdx
- website/src/pages/v3/migration/migration-from-express-graphql.mdx
- website/src/pages/v3/migration/migration-from-yoga-v1.mdx
- website/src/pages/v3/migration/migration-from-yoga-v2.mdx
- Drop all `sidebar_label`
- Use `Comparison` instead of `Comparison with other JavaScript GraphQL server libraries` in the sidebar
- Use `Yoga v3` instead of `Migration from Yoga V2` in the sidebar (match naming)
> frontMatter `sidebar_label` is unused and smaller sidebar titles adjustments

- .changeset/@graphql-yoga_plugin-apollo-inline-trace-1746-dependencies.md
- .changeset/@graphql-yoga_plugin-apollo-inline-trace-1753-dependencies.md
- .changeset/@graphql-yoga_plugin-apq-1746-dependencies.md
- .changeset/@graphql-yoga_plugin-apq-1753-dependencies.md
- .changeset/fifty-elephants-provide.md
- .changeset/graphql-yoga-1746-dependencies.md
- .changeset/graphql-yoga-1753-dependencies.md
- examples/defer-stream/src/index.ts
- examples/graphql-armor/src/main.ts
- examples/hello-world/README.md
- packages/graphql-yoga/__tests__/http-extensions.spec.ts
- packages/graphql-yoga/package.json
- packages/graphql-yoga/src/plugins/useSchema.ts
- packages/graphql-yoga/src/server.ts
- website/src/pages/v3/features/envelop-plugins.mdx
- website/src/pages/v3/features/error-masking.mdx
- website/src/pages/v3/features/file-uploads.mdx
- website/src/pages/v3/features/response-caching.mdx
- website/src/pages/v3/features/subscriptions.mdx
- website/src/pages/v3/index.mdx
- website/src/pages/v3/integrations/integration-with-sveltekit.mdx
- website/src/pages/v3/migration/migration-from-apollo-server.mdx
- website/src/pages/v3/migration/migration-from-yoga-v1.mdx
- Remove `getDefaultSchema`
- No longer set a default schema
- No longer accept `{ typeDefs, resolvers }` but use `createSchema({ typeDefs, resolvers })` instead
So Yoga won't have `@graphql-tools/schema` in the bundle if schema is created in a different way.
> Don't accept an object of typeDefs and resolvers

- e2e/tests/docker.ts
- examples/node-ts/__integration-tests__/node-ts.spec.ts
- examples/node-ts/build.js
- examples/node-ts/package.json
- examples/node-ts/src/yoga.ts
closes https://github.com/dotansimha/graphql-yoga/issues/1015
> ci: run docker test only

- examples/netlify-edge/.gitignore
- examples/netlify-edge/.netlify/edge-functions-import-map.json
- examples/netlify-edge/.netlify/state.json
- examples/netlify-edge/__integration-tests__/netlify-edge.spec.ts
- examples/netlify-edge/build.js
- examples/netlify-edge/package.json
- examples/netlify-edge/src/index.ts
made it so we first bundle everything needed for the edge function. This way we can test the local versions and no need to rely on a CDN. Now we can simply just tests the integration.
closes https://github.com/dotansimha/graphql-yoga/issues/1515
> test: integration for netlify-edge

- website/src/pages/v3/migration/migration-from-yoga-v2.mdx
- Use headings for sections
- Drop duplicate `graphqlEndpoint` section
- Smaller wording changes
> Improved migration from v2 guide

- packages/graphql-yoga/__tests__/schema.spec.ts
- packages/graphql-yoga/src/plugins/types.ts
- packages/graphql-yoga/src/plugins/useSchema.ts
- packages/graphql-yoga/src/server.ts
Technically, `GraphQLSchema` is not needed until Yoga continues with the regular execution pipeline.
For example; The user provides a factory function to set a schema per request. But that function was being called even if the execution pipeline is stopped earlier by another plugin within `onRequest`.
So this PR changes this behavior by moving the schema resolution from `onRequest` to `onParams`.
> Resolve the schema only if needed

- .changeset/breezy-ads-walk.md
- packages/graphql-yoga/package.json
- yarn.lock
we only used a type from `@graphql-tools/utils` in our tests and not actaully using it anywhere so no need for end users to install it.
> chore: remove `@graphql-tools/utils` as dep

- .changeset/healthy-lizards-walk.md
- examples/graphql-ws/__integration-tests__/graphql-ws.spec.ts
- packages/graphql-yoga/src/plugins/requestValidation/usePreventMutationViaGET.ts
- packages/graphql-yoga/src/server.ts
- website/src/pages/v3/features/subscriptions.mdx
If you supply a malformed/unexpected context value to Yoga's envelop instance like this: `yoga.getEnveloped({})` - everything breaks because Yoga depends on the `params` being present in the context and envelop's typings don't require the correct context.
This PR considers, and properly handles, the fact that the `params` might be missing in some cases.
Also updated the `graphql-ws` example to show a correctly formatted context.
> User might supply malformed context to getEnveloped and fix graphql-ws example

- .changeset/fast-coats-explode.md
- packages/graphql-yoga/__tests__/requests.spec.ts
- packages/graphql-yoga/src/plugins/requestParser/utils.ts
@charlypoly discovered that sometimes a client misbehaves and provides a list of values in the `Content-Type` header. This is not valid as per the HTTP spec, but the culprits don't care...
> Handle edge case where Content-Type header provides a list

- .changeset/eighty-crabs-stare.md
- packages/common/__tests__/graphiql.test.ts
- packages/common/src/plugins/useGraphiQL.ts
fix for https://github.com/dotansimha/graphql-yoga/issues/1964
added `await` for `graphiqlOptionsFactory` return value which may be a Promise
> Fixed graphiql ignoring options if `GraphiQLOptionFactory` returns Promise

- .changeset/sweet-paws-kiss.md
- examples/defer-stream/__integration-tests__/defer-stream.spec.ts
- packages/graphql-yoga/src/plugins/resultProcessor/accept.ts
- packages/graphql-yoga/src/plugins/types.ts
- packages/graphql-yoga/src/plugins/useResultProcessor.ts
- packages/graphql-yoga/src/process-request.ts
- packages/graphql-yoga/src/server.ts
Yoga was choosing the processor according to the order we have in our internal plugins but it should respect the order of the accept header instead.
And also Yoga was ignoring other mime types in the accept header because the last accepted procesor was always chosen.
For example if there is an asynciterable result but `application/json, multipart/mixed` is given then Yoga chooses `json` no matter what then fails because `json` processor cannot process async iterables.
> fix: respect the order in the accept header

- .changeset/smart-pens-compete.md
- packages/graphql-yoga/src/validations/overlapping-fields-can-be-merged.ts
utils are internal in `graphql-js` and importing this way we are basically breaking different variants of `graphql-js` this allows us to use across version
> support older graphql js version

- .changeset/curly-pugs-remain.md
- packages/graphql-yoga/__tests__/logging.spec.ts
- packages/graphql-yoga/package.json
- packages/graphql-yoga/src/server.ts
- packages/graphql-yoga/src/types.ts
- packages/graphql-yoga/type-api-check.ts
- pnpm-lock.yaml
- website/src/pages/v3/migration/migration-from-yoga-v2.mdx
we recommend using `fetch` so we should remove this.
> remove inject method

- examples/issue-template/package.json
- pnpm-lock.yaml
> chore: add @types/node as dev dep

- packages/graphql-yoga/__tests__/logging.spec.ts
- packages/graphql-yoga/__tests__/logging.ts
- packages/graphql-yoga/src/error.ts
- packages/graphql-yoga/src/server.ts
closes https://github.com/dotansimha/graphql-yoga/issues/1584
> feat: log unexpected GraphQL errors

- .changeset/thin-rings-buy.md
- packages/graphql-yoga/src/index.ts
after some thought I think we should really only export selective things from `@envelop/core` instead of exporting everything. This way we avoid any breaking changes downstream envelop impacting us. 
closes https://github.com/dotansimha/graphql-yoga/issues/2039
> chore: re-export specific things from @envelop/core

- packages/graphql-yoga/__tests__/logging.spec.ts
- packages/graphql-yoga/__tests__/logging.ts
- packages/graphql-yoga/src/logger.ts
- packages/graphql-yoga/src/server.ts
- website/src/pages/v3/features/logging-and-debugging.mdx
This allows providing a log-level string to the `logging` option.
It also changes the behavior that allows the `DEBUG` environment variable mixture with different log levels. If the `DEBUG` environment variable is specified, all logs (prior log levels) should be logged instead.
I don't really see a use case where I want `debug` logs but not `info` and/or `warn` logs.
> feat: log level via config

- packages/graphql-yoga/README.md
I discovered that links to the examples in the README aren't valid. This PR fixes it 🚀
> docs(README): fix invalid examples link

- website/src/pages/docs/features/subscriptions.mdx
I was trying out a rewrite to Yoga through through the documentation examples and my Apollo Client custom config looked pretty close to the example but it was failing for SSE requests. It turns out my request was being stringified twice so it would go from `analyticEvent` to `"analyticEvent"` and when adding that to the URL params it was coming back with 
```
data: {"errors":[{"message":"Could not determine what operation to execute."}]}
```
> docs: fix example typo

- .changeset/slimy-kings-confess.md
- packages/graphql-yoga/src/plugins/useCORS.ts
- packages/graphql-yoga/src/plugins/useCors.spec.ts
> fix(cors): add content-length: 0 header if 204 is returned by OPTIONS request

- .changeset/graphql-yoga-2231-dependencies.md
- package.json
- packages/graphql-yoga/package.json
- packages/plugins/disable-introspection/__tests__/disable-introspection.spec.ts
- packages/plugins/disable-introspection/package.json
- packages/plugins/disable-introspection/src/index.ts
- pnpm-lock.yaml
- website/src/pages/docs/features/introspection.mdx
~~Tests are failing because the `useValidationCache` plugin from envelope does not include the rules in the cache key.~~
See https://github.com/n1ru4l/envelop/pull/1598
Closes https://github.com/dotansimha/graphql-yoga/issues/2188
> feat: disable introspection plugin

- .changeset/eighty-crabs-stare.md
- packages/graphql-yoga/src/plugins/useGraphiQL.spec.ts
- packages/graphql-yoga/src/plugins/useGraphiQL.ts
from https://github.com/dotansimha/graphql-yoga/pull/1747#issuecomment-1325837265
Port #1965 for v3
> [v3] Fixed graphiql ignoring options if GraphiQLOptionFactory returns Promise

- .changeset/wise-geckos-beam.md
- packages/graphql-yoga/src/plugins/resultProcessor/push.ts
Closes https://github.com/dotansimha/graphql-yoga/issues/2095
> Ping/pong for SSE

- website/src/pages/docs/features/persisted-operations.mdx
The examples later in this doc reference `@graphql-yoga/plugin-persisted-operations` and were throwing errors when using `@graphql-yoga/persisted-operations`, which appears to install an older version of the plugin.
> Fix install instructions for persisted operations

- .changeset/thirty-peaches-dress.md
- packages/graphql-yoga/src/plugins/useGraphiQL.ts
Fixes https://github.com/dotansimha/graphql-yoga/issues/2132#issuecomment-1368916343
> fix(graphiql): use `location.href` instead of `graphqlEndpoint` from Yoga

- .changeset/long-pandas-joke.md
- .changeset/polite-owls-judge.md
- examples/graphql-sse/package.json
- examples/graphql-sse/src/app.ts
- examples/graphql-sse/src/index.ts
- examples/graphql-sse/tsconfig.json
- packages/graphql-yoga/src/plugins/types.ts
- packages/graphql-yoga/src/plugins/useGraphiQL.ts
- packages/graphql-yoga/src/server.ts
- packages/plugins/graphql-sse/__tests__/graphql-sse.spec.ts
- packages/plugins/graphql-sse/package.json
- packages/plugins/graphql-sse/src/index.ts
- pnpm-lock.yaml
- website/src/pages/docs/comparison.mdx
- website/src/pages/docs/features/subscriptions.mdx
Closes #2138 
Closes #2279
New Yoga plugin named `@graphql-yoga/plugin-graphql-sse` allowing for full [GraphQL over Server-Sent Events](https://github.com/enisdenjo/graphql-sse/blob/master/PROTOCOL.md) support through [graphql-sse](https://github.com/enisdenjo/graphql-sse).
> graphql-sse plugin

- website/src/pages/docs/comparison.mdx
The NPM package name `@apollo/server` has funky characters, so the generated HTTP link doesn't work correctly if the web address is not URL encoded
> docs: fix the link to see dependencies of Apollo Server

- .changeset/old-spiders-perform.md
- examples/apollo-federation/__integration-tests__/apollo-federation.spec.ts
- examples/apollo-federation/gateway/gateway.js
- examples/apollo-federation/service/yoga.js
- packages/graphql-yoga/src/index.ts
- packages/graphql-yoga/src/server.ts
- packages/graphql-yoga/src/utils/mask-error.ts
- website/src/pages/docs/features/apollo-federation.mdx
- website/src/pages/docs/features/error-masking.mdx
See https://github.com/dotansimha/graphql-yoga/discussions/2363
> feat: export the mask error function + gateway notes

- .changeset/@graphql-yoga_urql-exchange-2137-dependencies.md
- .changeset/strange-beers-promise.md
- examples/defer-stream/__integration-tests__/__snapshots__/defer-stream.spec.ts.snap
- packages/client/urql-exchange/package.json
- packages/graphql-yoga/src/plugins/resultProcessor/multipart.ts
- packages/plugins/defer-stream/__tests__/defer-stream.spec.ts
- packages/plugins/defer-stream/package.json
- pnpm-lock.yaml
- website/src/pages/docs/features/testing.mdx
Fixes https://github.com/dotansimha/graphql-yoga/issues/2243
> Document HTTP Executor & Fix ending multipart requests

- website/src/pages/docs/features/testing.mdx
Note that we now also have the section for `@graphql-tools/http-executor`.
It would be great if  `@graphql-tools/http-executor` could infer types from `TypedDocumentNode`.
> docs: add section for codegen client preset

- website/src/pages/docs/features/introspection.mdx
The GraphQL Code Generator hyperlink seems to be broken. The actual link that is working is: https://the-guild.dev/graphql/codegen
> Use non-www to the codegen website

- website/src/components/codegen-callout.mdx
- website/src/pages/docs/index.mdx
This PR adds a callout at the bottom of Quick Start guide's Schema section to promote GraphQL Codegen and server preset:
> Add callout from Quick Start to GraphQL Codegen and server preset

- .changeset/@graphql-yoga_graphiql-2425-dependencies.md
- benchmark/hello-world/k6.js
- packages/graphql-yoga/src/plugins/requestParser/GET.ts
- packages/graphql-yoga/src/plugins/types.ts
- packages/graphql-yoga/src/plugins/useCORS.ts
- packages/graphql-yoga/src/plugins/useCors.spec.ts
- packages/graphql-yoga/src/plugins/useGraphiQL.ts
- packages/graphql-yoga/src/plugins/useHealthCheck.ts
- packages/graphql-yoga/src/plugins/useParserAndValidationCache.ts
- packages/graphql-yoga/src/plugins/useReadinessCheck.ts
- packages/graphql-yoga/src/plugins/useRequestParser.ts
- packages/graphql-yoga/src/plugins/useUnhandledRoute.ts
- packages/graphql-yoga/src/server.ts
- packages/plugins/graphql-sse/__tests__/graphql-sse.spec.ts
- packages/plugins/prometheus/tests/prometheus.spec.ts
Also benchmarks will use `POST` just like graphql-crystal's benchmarks. And `POST` doesn't use `URL` in this basic example so it never uses URL parsing.
> Replace LRU caching with lazy URL construction, avoid unnecessary `parse` and `validate` invocation and CORS

- .changeset/tame-frogs-shake.md
- examples/response-cache/__integration-tests__/response-cache.spec.ts
- examples/response-cache/package.json
- examples/response-cache/src/main.ts
- examples/response-cache/tsconfig.json
- packages/graphql-yoga/src/plugins/types.ts
- packages/graphql-yoga/src/process-request.ts
- packages/plugins/response-cache/__tests__/etag.spec.ts
- packages/plugins/response-cache/__tests__/response-cache.spec.ts
- packages/plugins/response-cache/src/index.ts
- pnpm-lock.yaml
- website/src/pages/docs/features/response-caching.mdx
Closes https://github.com/dotansimha/graphql-yoga/issues/2080
> feat(response-cache): use ETag to use HTTP caching strategy

- .changeset/plugin-persisted-operations-dependencies.md
- packages/plugins/persisted-operations/package.json
Fix @graphql-tools/utils peerDependencies compatibility 9.2.1
conflicting peer dependency: @graphql-tools/utils@9.2.1 node_modules/@graphql-tools/utils
peer @graphql-tools/utils@"^9.0.1" from @graphql-yoga/plugin-persisted-operations@1.7.0
> Fix utils@9.2.1

- website/src/pages/docs/features/health-check.mdx
I thought it might be 503, not 504.
https://github.com/dotansimha/graphql-yoga/blob/d6f98687d7e5cf0377312b79be6fa3460b84f905/packages/graphql-yoga/src/plugins/useReadinessCheck.ts#L18
> docs: Fix readiness http status code to `503`

- packages/graphql-yoga/__integration-tests__/node-http.spec.ts
Related https://github.com/dotansimha/graphql-yoga/issues/2655
Went down this rabbit hole trying to identify root cause of odd behaviour of status texts in graphql-yoga. This doesn't make any non-test changes, but given that I've written these tests now I thought they may be helpful to prevent future regressions so figured would at least submit the PR :)
> Add more tests validating different statuses

- .changeset/spotty-singers-suffer.md
- packages/plugins/persisted-operations/__tests__/persisted-operations-errors.spec.ts
- packages/plugins/persisted-operations/__tests__/persisted-operations.spec.ts
- packages/plugins/persisted-operations/src/index.ts
- website/src/pages/docs/features/persisted-operations.mdx
This PR aims to allow the customization of errors in Persisted Operations plugin.
fixes #2047 
I have implemented multiple ways to customize errors with polymorphic options. I'm not sure if this wanted, since it seems this pattern is not heavily used in the code base. But I think it can be a good DX, since the most general use-case will probably to add a static extensions such as HTTP status.
Don't hesitate If you have suggestion about option names, I'm not totally satisfied.
I also give access to the payload of the `onParams` function to the error factory. Perhaps I should filter to avoid passing setters and only give access to `params` and `request` ?
```ts filename="Customize errors"
import { createYoga } from 'graphql-yoga'
import { createServer } from 'node:http'
import { …
```
> Allow to customize persisted operations errors

- packages/plugins/persisted-operations/__tests__/persisted-operations.spec.ts
- website/src/pages/docs/features/persisted-operations.mdx
The Relay usage of Persisted Query is broken and the type used for `params` is misleading.
fixes #2756
> Fix documentation for using Persisted Queries with Relay

- import-map.json
- pnpm-lock.yaml
Fixes the CI by pining `@whatwg-node/events` in deno's import map.
> pin deno whatwg-node/events dependency

- pnpm-lock.yaml
- website/src/pages/docs/features/file-uploads.mdx
Improve the File upload quick start with a file upload to show how to get a Buffer containing the content of the file instead of just text handling.
I've also added a quick example showcasing an S3 file upload as it's a pretty common task.
fixes #2763
> add documentation to handle files as binary instead of text

- website/src/pages/docs/integrations/integration-with-aws-lambda.mdx
There was typo (duplicate bracket in the code example) for https://the-guild.dev/graphql/yoga-server/docs/integrations/integration-with-aws-lambda#example
> Fix code example - integration-with-aws-lambda.mdx

- .changeset/sweet-cheetahs-shop.md
- packages/plugins/persisted-operations/__tests__/persisted-operations.spec.ts
- packages/plugins/persisted-operations/src/index.ts
- website/src/pages/docs/features/persisted-operations.mdx
I have a requirement to support multiple persisted operation stores, dictated by a request header.
**_Change:_**
Pass `request` to `getPersistedOperation`
> Pass request to get persisted operations function

- .changeset/lovely-pants-laugh.md
- packages/graphql-yoga/__tests__/accept-header.spec.ts
- packages/graphql-yoga/src/plugins/use-result-processor.ts
Closes https://github.com/dotansimha/graphql-yoga/issues/2677
> feat: no subscription via multipart/mixed

- .changeset/purple-ravens-train.md
- packages/graphql-yoga/src/plugins/request-validation/use-http-validation-error.spec.ts
- packages/graphql-yoga/src/plugins/request-validation/use-http-validation-error.ts
my intention here is to throw 400 error on validation errors, but the native `useHTTPValidationError` is overriding my error, so this won't work on my side:
```js
await createYoga({
plugins: [
{
onValidate() {
return ({ valid, result }) => {
if (!valid) {
for (const error of result) {
error.extensions.http = {
status: 400,
spec: false
};
}
}
};
}
}
],
...the rest of the configuration
})
```
notice that this is an exact copy of `useHTTPValidationError` but with `spec: false` set.
On the other side, I am not finding what is the "spec" prop for, and I am not finding documentation for it. I would appreciate if you can enlight me on that topic.
> do not overwrite existing status on validation, if any

- .changeset/@graphql-yoga_plugin-response-cache-2887-dependencies.md
- .changeset/orange-grapes-exist.md
- packages/plugins/response-cache/__tests__/response-cache.spec.ts
- packages/plugins/response-cache/package.json
- pnpm-lock.yaml
- website/src/pages/docs/features/response-caching.mdx
Add a path to use configure response cache with a schema first approach.
This has been implemented in the envelop plugin, this PR is updates dependency and adds the relevant documentation to Yoga.
fixes #2187
> feat(plugin-response-cache): add @cacheControl compatibility

- website/src/pages/docs/integrations/integration-with-cloudflare-workers.mdx
- website/src/pages/tutorial/advanced/02-subscriptions.mdx
As mentioned in https://github.com/dotansimha/graphql-yoga/pull/2324#issuecomment-1387439123 🙂 
I also added a note about shared subscriptions to the subscriptions doc, as I was very confused at first on how to set up a chat-room like app with Yoga.
> Add reference to graphql-workers-subscriptions

- website/src/pages/docs/features/jwt.mdx
This PR fixes a minor, but fatal typo on the [JWT page](https://the-guild.dev/graphql/yoga-server/docs/features/jwt) — `useJwt` is changed to `useJWT`.
> Fix typo in JWT docs

- website/src/pages/docs/comparison.mdx
The table of comparison between runtime performances is not formated properly and displays raw markdown in the docs.
> docs: fix table layout in comparison.mdx

- website/src/pages/docs/features/schema.mdx
Corrected "Simply pass **an** schema..." to "Simply pass *a* schema..."
> fix: Fixed typo found in GraphQL Schema page of the features docs

- website/src/pages/docs/features/graphiql.mdx
- website/src/pages/docs/features/response-caching.mdx
Changed "...**an** user..." to "...**a** user..." in graphiql.mdx and removed duplicate "directive" in response-caching.mdx
> fix: Typos found in graphiql.mdx and response-caching.mdx

- website/src/pages/docs/integrations/integration-with-sveltekit.mdx
Updates the documentation to correctly show the needed values to make this work on SvelteKit
> Fix integration-with-sveltekit.mdx

- examples/hapi/__integration-tests__/hapi.spec.ts
- examples/hapi/src/app.ts
- website/src/pages/docs/integrations/integration-with-hapi.mdx
Fixes #2962
This PR implements the following:
1. Passing the entire raw `IncomingMessage` [request.raw](https://hapi.dev/api/?v=21.3.2#-requestraw) from hapi to `handleNodeRequest` instead of request.payload.
While request.payload works when graphQL API is queried directly using a POST request it does not work when `handleNodeRequest` tries to handle a GET request for a graphiql page.
2. Creates a hapi response that contains the `Readable` stream rather than directly returning a raw Readable stream.
Technically the previous implementation works it isn't how hapi response are usually formed. The previous implementation means that the headers are not returned in the response which results in `application/octet-stream` headers for GET request. (Meaning html page is just downloaded rather …
> Hapi example to support GraphiQL

- .changeset/fluffy-queens-lick.md
- packages/nestjs/__tests__/fixtures/graphql/cats/cats.resolvers.ts
- packages/nestjs/__tests__/fixtures/graphql/cats/cats.types.graphql
- packages/nestjs/__tests__/subscriptions.spec.ts
- packages/nestjs/src/index.ts
NestJS subscriptions' resolvers have a `filter` and a `resolve` function in the @Subscription decorator. Currently only the `resolve` is supported by the YogaDriver for NestJS.
This commit adds support for the `filter` method. The implementation is similar to NestJS Apollo plugin, but it uses Yoga's own async iterator utils (pipe, filter) instead of Apollo's utils.
> feat: Support NestJS `filter` function for subscriptions

- website/src/pages/docs/integrations/integration-with-deno.mdx
Hi, I tried GraphQL Yoga with Deno runtime.
I found that we can define the import map in the `deno.json` file.
https://deno.land/manual@v1.36.4/basics/import_maps#import-maps
I have updated the documentation to align with the current Deno specifications.
And, I have ensured the code is working appropriately.
https://github.com/motoya-k/deno-blog-sample/tree/main/packages/api
> docs: Update integration-with-deno.mdx

- .changeset/hungry-numbers-burn.md
- packages/plugins/response-cache/__tests__/response-cache.spec.ts
- packages/plugins/response-cache/src/index.ts
> fix type for in memory cache factory

- .changeset/wicked-feet-drop.md
- examples/generic-auth/src/app.ts
- packages/graphql-yoga/__tests__/schema.spec.ts
- packages/graphql-yoga/src/plugins/use-schema.ts
- packages/graphql-yoga/src/schema.ts
- packages/graphql-yoga/src/server.ts
- website/src/pages/docs/features/schema.mdx
> fix type and documentation for dynamic schema function

- .changeset/@graphql-yoga_plugin-response-cache-2993-dependencies.md
- .changeset/curly-walls-pretend.md
- .changeset/fifty-drinks-judge.md
- packages/plugins/response-cache/__tests__/response-cache.spec.ts
- packages/plugins/response-cache/package.json
- packages/plugins/response-cache/src/index.ts
- pnpm-lock.yaml
- website/src/pages/docs/features/response-caching.mdx
Adds support for the `scope` feature from Apollo's response cache plugin.
This PR is updating the underlying envelop plugin and fixes a bug preventing Envelop plugin to detect the presence of a session or not.
Fixes #3021
> [response-cache] update @envelop/response-cache with support of scope, defer and stream

- .changeset/@graphql-yoga_plugin-response-cache-3006-dependencies.md
- packages/plugins/defer-stream/__tests__/defer-stream.spec.ts
- packages/plugins/response-cache/__tests__/response-cache.spec.ts
- packages/plugins/response-cache/package.json
- packages/plugins/response-cache/src/index.ts
- pnpm-lock.yaml
- website/src/pages/docs/features/response-caching.mdx
> fix response cache usage with subscriptions

- .changeset/wise-goats-promise.md
- packages/plugins/jwt/src/index.ts
> [JWT] allow getToken to return a promise

- benchmark/package.json
- benchmark/start-server.ts
- examples/sveltekit/package.json
- packages/graphql-yoga/__tests__/custom-serializer.spec.ts
- packages/graphql-yoga/package.json
- packages/graphql-yoga/src/plugins/result-processor/stringify.ts
- packages/graphql-yoga/src/plugins/types.ts
- pnpm-lock.yaml
GraphQL JIT generates JSON Schemas from operations, and it provides a custom json stringify function to serialize execution results faster than JSON.stringify. This PR allows you to use a custom serializer by providing it in `stringify` prop
> feat: support custom serializers for execution results

- .changeset/wet-emus-bake.md
- packages/graphiql/src/bundle.tsx
we are already bundling `React` part of this package. I want to pass in the `logo` prop to customize the looks and just using HTML, this will make it so I don't have to improve `React` additionally from CDN I can just use it directly.
> feat: expose React in the window object

- .changeset/@graphql-yoga_plugin-response-cache-3092-dependencies.md
- .changeset/early-masks-try.md
- .changeset/pretty-numbers-fetch.md
- packages/plugins/response-cache/package.json
- packages/plugins/response-cache/src/index.ts
- pnpm-lock.yaml
Fix some missing exports.
fixes #3035
> fix missing export for Cache and directive

- .changeset/@graphql-yoga_apollo-link-3118-dependencies.md
- .changeset/@graphql-yoga_urql-exchange-3118-dependencies.md
- .changeset/ten-poems-fix.md
- packages/client/apollo-link/package.json
- packages/client/apollo-link/src/index.ts
- packages/client/urql-exchange/package.json
- packages/client/urql-exchange/src/index.ts
- packages/plugins/defer-stream/package.json
- pnpm-lock.yaml
https://github.com/ardatan/graphql-tools/pull/5724
> Bump @graphql-tools/executor-http for better SSE stream chunks and messages handling

- .changeset/kind-news-agree.md
- packages/plugins/response-cache/__tests__/response-cache.spec.ts
- packages/plugins/response-cache/package.json
- packages/plugins/response-cache/src/index.ts
- pnpm-lock.yaml
Fixes #3110 
Contains a NOTE: 
- https://github.com/dotansimha/graphql-yoga/pull/3135/files#diff-3767b3f7edc61174419a72a31a871482483efcc3ffa506f5785aec14a68dc7b3R1034
- This might be worth opening a new issue for? IDK if it seems correct, I did sure not expect it
> Make the warn log a debug log

- .changeset/old-wolves-arrive.md
- .changeset/red-lemons-prove.md
- packages/graphql-yoga/src/index.ts
- packages/nestjs/__tests__/graphql.spec.ts
- packages/nestjs/package.json
- packages/nestjs/src/index.ts
- pnpm-lock.yaml
In the current implementation of graphql-yoga, users have the flexibility to pass a function to the schema property, facilitating the setup of a conditional schema. Unfortunately, this functionality is not mirrored in the @graphql-yoga/nestjs package, creating a limitation when working with frameworks like Nest.JS, which appears to have restricted support for conditional schemas in the GraphQLModule.
At [Twenty](https://github.com/twentyhq/twenty), we have a specific requirement to determine schemas dynamically based on the tenant to [enable custom objects for our customers](https://github.com/twentyhq/twenty/discussions/1142). The absence of this feature in the @graphql-yoga/nestjs package hinders our ability to provide a more personalized and scalable service.
To bridge this gap, I have …
> feat: Implementing Conditional Schema Support in @graphql-yoga/nestjs

- .changeset/thirty-seas-attack.md
- packages/plugins/jwt/src/__tests__/jwt.spec.ts
- packages/plugins/jwt/src/index.ts
The JWT plugin was parsing and checking the jwt token in the `onRequest` hook. The implementation was simply throwing an error when not authenticated or on bad jwt token. The problem is that errors thrown in `onRequest` hook are not handled by yoga and are bubling up directly to the actual HTTP server implementation.
When using `express`, `koa` or `fastify`, this was resulting in a response with `500` status code.
When using Node's http server, this was resulting in simply crashing the server.
To fix this, we should always using `onRequestParse` over `onRequest`.
fixes #3147
> [jwt] fix unauthorized being thrown in `onRequest`

- .changeset/long-weeks-rest.md
- packages/plugins/csrf-prevention/__tests__/csrf-prevention.spec.ts
- packages/plugins/csrf-prevention/src/index.ts
The current version of the CSRF prevention plugin requires special headers to be present on all requests. However in order to prevent CSRF attacks the check must only be done on some requests. For POST requests the browser does automatic preflight checks already for all content types not matching `application/x-www-form-urlencoded`,   `multipart/form-data`, `text/plain`
> fix: Apply CSRF prevention validation only to GET requests

- .changeset/big-tables-clean.md
- packages/plugins/response-cache/__tests__/response-cache.spec.ts
- packages/plugins/response-cache/src/index.ts
Add `servedFromResponseCache` symbol property to responses served from the response cache in order
to allow other plugins to determine, whether a response was served from the cache and apply custom
logic based on that.
This is required for solving https://github.com/kamilkisiela/graphql-hive/issues/3807
> feat: add served from response cache symbol to response cache

- website/src/pages/docs/features/envelop-plugins.mdx
add flow diagram and all hooks in the plugin system
> docs: add flow diagram and all hooks in the plugin system

- website/src/pages/docs/integrations/integration-with-bun.mdx
Update documentation to match correct way to use this with Bun.js
Issue: https://github.com/dotansimha/graphql-yoga/issues/3003
> Documentation: fix params of Bun.serve to use yoga  issue #3003

- .changeset/dull-numbers-work.md
- .changeset/two-beds-listen.md
- packages/plugins/prometheus/package.json
- packages/plugins/prometheus/src/index.ts
- packages/plugins/prometheus/tests/prometheus.spec.ts
- website/src/pages/docs/integrations/integration-with-bun.mdx
Prometheus has issues with cardinality where metrics with many labels causes a large number of data points and impacts performance, for this reason its generally good practice not to include unbounded labels in metrics. 
This PR addresses two issues: 
1. A bug in the plugin where if operationName was not added as a label the server errors on requests.
2. Remove metrics that will result in a label cardinality issue. 
This does mean, `url`, `statusText`, `http headers` will no longer be labels in metrics.
> remove high cardinality labels and fix bug for operationName

- website/src/pages/docs/features/defer-stream.mdx
Fixing 2 minor typos in Defer and Stream documentation
> defer-stream.mdx typos

- .changeset/graphql-yoga-3237-dependencies.md
- .changeset/smart-melons-beam.md
- packages/graphql-yoga/__tests__/requests.spec.ts
- packages/graphql-yoga/package.json
- packages/graphql-yoga/src/server.ts
- pnpm-lock.yaml
Closes https://github.com/dotansimha/graphql-yoga/issues/3238
> Unique execution context with the correct request object

- website/src/pages/docs/features/graphiql.mdx
- website/src/pages/docs/features/response-caching.mdx
This PR includes a setence correction/update that includes that when in development graphiql is accessible on the `/graphql` endpoint and not when in production, unless the graphiql option is  updated.
This PR referenes #3158
> Indicating graphiQL default status when in production

- .changeset/silly-pigs-rhyme.md
- packages/graphql-yoga/__tests__/context.spec.ts
- packages/graphql-yoga/src/server.ts
I am using graphql-yoga with Koa, and I want to pass a server context object with a prototype to `handleNodeRequest`. This works for regular requests, but for batched requests, the prototype is lost, and only the enumerable properties get copied to the request-specific context objects. This change makes it so that batched requests use `Object.create` for the extended context instead of an empty object.
> Retain server context prototype for batched requests

- .changeset/rotten-knives-remember.md
- packages/graphiql/README.md
- packages/graphiql/src/YogaGraphiQL.tsx
- packages/graphql-yoga/src/plugins/use-graphiql.ts
This PR added support for the `shouldPersistHeaders` option to the graphiql plugin.
> feat: support shouldPersistHeaders option in GraphiQL plugin

- website/src/pages/docs/features/automatic-persisted-queries.mdx
Solves https://github.com/dotansimha/graphql-yoga/issues/3204
> (docs): Provide example for APQ in case of outage

- .changeset/rotten-chefs-love.md
- packages/plugins/prometheus/src/index.ts
- packages/plugins/prometheus/tests/prometheus.spec.ts
- website/src/pages/docs/features/automatic-persisted-queries.mdx
To fill labels, the plugin is caching operation params using the `onExecute` hook. This leads to params missing when the operation is not executed (such as for invalid operation with unknown fields for example).
This PR uses `onParse` hook instead.
fixes #3274
> [plugin/prometheus] fix labels not filled properly on invalid operations

- .changeset/stale-geckos-draw.md
- packages/plugins/jwt/src/index.ts
- website/src/pages/docs/features/automatic-persisted-queries.mdx
Current type of the plugin options offer only a limited set of options to verify the JWT. This PR updates the type to allow passing all options offered by `jsonwebtoken`
> [plugin/jwt] allow passing all verify options

- examples/bun-yoga-ws/__integration-tests__/bun.spec.ts
- examples/bun-yoga-ws/package.json
- examples/bun-yoga-ws/src/index.ts
- examples/bun-yoga-ws/tsconfig.json
This PR provides an example of integrating GraphQL subscriptions using WebSockets in BunJS, leveraging `makeHandler` api provided by graphql-ws. 
👉 https://github.com/dotansimha/graphql-yoga/discussions/3041
> chore(example): Implement GraphQL Subscriptions with Yoga and WebSockets in BunJS

- .changeset/graphql-yoga-3170-dependencies.md
- examples/bun/__integration-tests__/bun.spec.ts
- pnpm-lock.yaml
fixes bun integration issues where the context is shared between all requests.
> [integration/bun] add tests for shared context

- .changeset/lovely-ladybugs-build.md
- packages/plugins/jwt/src/index.ts
- pnpm-lock.yaml
I noticed the `JwksClient` from `jwks-rsa` has quite a few options which are not made available in the `useJWT` config properties. For my particular use case, I was wanting access to [`getKeysInterceptor`](https://github.com/auth0/node-jwks-rsa/blob/4fe372be935c2aa0882e0f1e58d33eead4be966d/EXAMPLES.md?plain=1#L30) so that I could intercept jwks loading in my test suite.
However, rather than attempt to add support for just one or all of these options, I thought it would be best to allow the user to specify _any_ of these client options by directly referencing its type and merging those props with the props passed to the `JwksClient` constructor.
I wasn't clear on whether I could easily add test coverage for this, because it doesn't appear that any of the coverage is directly using a real …
> useJWT plugin: allow overriding any JwksClient options

- .changeset/kind-fireants-rush.md
- packages/graphiql/src/YogaGraphiQL.tsx
- packages/graphql-yoga/src/plugins/use-graphiql.ts
The current wrapper for GraphiQL restricts which options can be passed to the underlying GraphiQL components (while advertised otherwise by the types).
This PR aims to propagate all options to GraphiQL.
It also adds every serializable options to the Yoga plugin, for easier customization without rolling out a entire custom renderer.
> [graphiql] Allow for full customization of GraphiQL

- website/src/pages/tutorial/_meta.ts
tiny change to not have nested folder
> add `display: children` for basic tutorials

- website/src/pages/docs/integrations/integration-with-uwebsockets.mdx
This PR fixes these TypeScript errors in the µWebSockets.js example in the docs: https://the-guild.dev/graphql/yoga-server/docs/integrations/integration-with-uwebsockets
> docs: µWebSockets.js listen params

- website/src/pages/docs/features/apollo-federation.mdx
We don't use `@apollo/gateway` or the Envelop plugin anymore.
> Remove `@apollo/gateway` reference

- .changeset/unlucky-cats-lie.md
- packages/graphql-yoga/__tests__/404.spec.ts
- packages/graphql-yoga/src/index.ts
- packages/graphql-yoga/src/plugins/use-unhandled-route.ts
- packages/graphql-yoga/src/server.ts
- packages/nestjs/__tests__/graphql-http.spec.ts
- website/src/pages/docs/features/_meta.ts
- website/src/pages/docs/features/landing-page.mdx
Customize the landing page by passing a custom renderer that returns `Response` to the `landingPage`
option
Then we can customize the landing page for Mesh etc.
> feat: customize landing page via `landingPage`

- .changeset/eighty-books-wonder.md
- packages/graphql-yoga/__tests__/requests.spec.ts
- packages/graphql-yoga/src/plugins/request-validation/use-check-graphql-query-params.ts
- packages/graphql-yoga/src/server.ts
- website/src/pages/docs/features/_meta.ts
- website/src/pages/docs/features/request-customization.mdx
By default, Yoga does not allow extra parameters in the request body other than `query`, `operationName`, `extensions`, and `variables`, then throws 400 HTTP Error.
This change adds a new option called `extraParamNames` to allow extra parameters in the request body.
```ts
import { createYoga } from 'graphql-yoga';
const yoga = createYoga({
/* other options */
extraParamNames: ['extraParam1', 'extraParam2'],
});
const res = await yoga.fetch('/graphql', {
method: 'POST',
headers: {
'Content-Type': 'application/json',
},
body: JSON.stringify({
query: 'query { __typename }',
extraParam1: 'value1',
extraParam2: 'value2',
}),
});
console.assert(res.status === 200);
```
> feat: allow extra params in body

- .changeset/chilly-poets-bathe.md
- packages/plugins/persisted-operations/__tests__/persisted-operations.spec.ts
- packages/plugins/persisted-operations/src/index.ts
According to the [GraphQL Yoga Context](https://the-guild.dev/graphql/yoga-server/docs/features/context#default-context), the default provided values in params includes `query`, `operationName`, `variables`, and `extensions`. When following the [the APQ Specification of Apollo](https://github.com/apollographql/apollo-link-persisted-queries#apollo-engine), the client sends `operationName` within the request, which would be helpful to keep in the context values if already exist. The current implementation strips the provided `operationName` value. I think it would be a good idea to add one, what do you think?
> fix(persisted-operations): include  in context params

- website/src/pages/docs/features/response-caching.mdx
https://the-guild.dev/graphql/yoga-server/docs/features/response-caching#enforce-session-based-caching
```diff
- 'User: 'PRIVATE' // Unterminated string literal.
+ User: 'PRIVATE'
```
> docs(typo): remove extra quotation

- .changeset/@graphql-yoga_plugin-sofa-3381-dependencies.md
- .changeset/slow-planes-battle.md
- .github/workflows/pr.yml
- packages/plugins/sofa/package.json
- packages/plugins/sofa/src/index.ts
- packages/plugins/sofa/tests/sofa.test.ts
Fix the existence of `request` in the context
> fix(sofa): `request` in the context

- .changeset/light-pants-protect.md
- examples/defer-stream/__integration-tests__/__snapshots__/defer-stream.spec.ts.snap
- packages/graphql-yoga/src/plugins/result-processor/multipart.ts
- packages/plugins/defer-stream/__integration-tests__/defer-stream.spec.ts
- packages/plugins/defer-stream/__tests__/defer-stream.spec.ts
- packages/plugins/defer-stream/package.json
Closes https://github.com/dotansimha/graphql-yoga/issues/3399
Restores compatibility with [RFC1341: The Multipart Content-Type](https://www.w3.org/Protocols/rfc1341/7_2_Multipart.html) by include preceding `\r\n` for initial boundary delimiter when using the multipart response protocol.
This makes Yoga compatible with libraries that strictly follow the response protocol, such as [fetch-multipart-graphql](https://github.com/relay-tools/fetch-multipart-graphql).
> fix: multipart response specification compatibility

- .changeset/cuddly-needles-cry.md
- packages/plugins/prometheus/src/index.ts
- packages/plugins/prometheus/tests/prometheus.spec.ts
- website/src/pages/docs/features/_meta.ts
- website/src/pages/docs/features/monitoring.mdx
By default, the following metrics are now enabled:
- `graphql_envelop_deprecated_field`
- `graphql_envelop_request`
- `graphql_envelop_request_duration`
- `graphql_envelop_request_time_summary`
- `graphql_envelop_phase_parse`
- `graphql_envelop_phase_validate`
- `graphql_envelop_phase_context`
- `graphql_envelop_error_result`
- `graphql_envelop_phase_execute`
- `graphql_envelop_phase_subscribe`
- `graphql_envelop_schema_change`
- `graphql_yoga_http_duration`
> Change default config for Prom metrics

- website/src/pages/docs/features/jwt.mdx
Fix code examples. 
useJWT config;
- lookupLocations -> tokenLookupLocations
- extendContext: true, -> according to TS this is either a boolean or string, so I assume give it a string to customize the field?
Came across these while implementing this awesome plugin 💚
> docs: update jwt.mdx - useJWT config field names & options

- packages/graphql-yoga/src/graphiql.html
see documentation https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cross-Origin-Embedder-Policy#avoiding_coep_blockage_with_cors
> fix: add `crossorigin` link attribute

- examples/redis-pub-sub/src/main.ts
- website/src/pages/docs/features/response-caching.mdx
This PR:
- Fixes the incorrect `Redis` import from `ioredis` npm library in examples. See [here](https://github.com/redis/ioredis?tab=readme-ov-file#basic-usage) for the correct usage from the ioredis docs
> fix: update ioredis import

- .changeset/changelog.md
- .changeset/early-ghosts-pump.md
- package.json
- packages/graphql-yoga/package.json
- packages/graphql-yoga/scripts/inject-version.js
- packages/graphql-yoga/src/landing-page.html
- packages/graphql-yoga/src/server.ts
- packages/plugins/apollo-usage-report/src/index.ts
Client name and version is missing now in Apollo Studio for traces which are sent by this plugin and is not possible to filter metrics by that.
> feat(apollo-usage-report): send Apollo clientName and clientVersion with trace

- .changeset/changelog1.md
- .changeset/changelog2.md
- package.json
- packages/plugins/apollo-usage-report/src/index.ts
Fixes issues mentioned in PR https://github.com/dotansimha/graphql-yoga/pull/3448
1. yoga version is not propagated well and string `__YOGA_VERSION__` is sent to the trace
2. `clientName` and `clientVersion` **should not have any default values**, because it is real identification of client (mobile app, web, ...). The client can send only the `name` or both (`name` and `version`) or  even "nothing". Setting the default values in this case can make a lot of confusion and if the client does not send this information (`name` or `version`) any default values should not be definitely set!
3. from this point of view, it doesn't make sense to add `clientName` and `clientVersion` to `type ApolloUsageReportOptions` as a`string` (custom function is good idea 👍 )
> Fix for issues mentioned in PR #3448

- .changeset/chatty-lobsters-exercise.md
- .changeset/quiet-cougars-camp.md
- packages/graphql-yoga/__tests__/plugin-hooks.spec.ts
- packages/graphql-yoga/src/plugins/types.ts
- packages/graphql-yoga/src/server.ts
- packages/plugins/persisted-operations/src/index.ts
Alternative approach for https://github.com/dotansimha/graphql-yoga/pull/3463
This is required for solving https://github.com/graphql-hive/platform/pull/5875 as the request can not be used as a internal cache key for batched requests.
> feat: pass context to onParams hook

- .changeset/changelog1.md
- .changeset/changelog2.md
- package.json
- packages/plugins/apollo-inline-trace/__tests__/apollo-inline-trace.yoga-gateway.spec.ts
- packages/plugins/apollo-inline-trace/__tests__/fixtures/getStitchedSchemaFromLocalSchemas.ts
- packages/plugins/apollo-inline-trace/__tests__/fixtures/subgraph1.ts
- packages/plugins/apollo-inline-trace/__tests__/fixtures/subgraph2.ts
- packages/plugins/apollo-inline-trace/package.json
- packages/plugins/apollo-inline-trace/src/index.ts
- pnpm-lock.yaml
If non-nullable field in GQL schema throw an error then the tracing plugin is not able to find correct trace node by its path and throw an error [here](https://github.com/dotansimha/graphql-yoga/blob/708d908a8c2b34d267738faeafd37c995d68ed1b/packages/plugins/apollo-inline-trace/src/index.ts#L364).
See the details in test called `'FAILING TEST - nonNullableFail - simple query - tracing plugin will throw "Could not find node with path testNestedField.failing" error'` in this PR.
I am not sure what is the reason why the path is missing in the "ctx.nodes", but probably the reason is that:
https://spec.graphql.org/draft/#sel-GAPHRPTCAACEzBg6S
> If the field which experienced an error was declared as Non-Null, the null result will bubble up to the next nullable field.
- assign an error to the …
> apollo-inline-trace - tracing should not fail if non-nullable field throw an error

- .changeset/graphql-yoga-3491-dependencies.md
- .changeset/pink-snails-thank.md
- package.json
- packages/graphql-yoga/__tests__/batching.spec.ts
- packages/graphql-yoga/package.json
- packages/graphql-yoga/src/server.ts
- website/src/pages/docs/features/envelop-plugins.mdx
- website/src/pages/docs/features/jwt.mdx
While investigating an issue for usage reporting for batched requests, I realized that context assignments for one batch execution to one context are also shared/assigned to the other batch contexts.
~~`Object.create` creates a new object using the existing object as the prototype so the assignments seem to be inherited. 🫤~~ 
~~This bug was introduced in https://github.com/dotansimha/graphql-yoga/pull/3270~~ 
This bug originates from `@whatwg-node/server` See https://github.com/ardatan/whatwg-node/pull/1797 and https://github.com/ardatan/whatwg-node/pull/1796).
> fix: context properties are shared between batched requests

- .changeset/@graphql-yoga_apollo-link-3501-dependencies.md
- .changeset/@graphql-yoga_graphiql-3501-dependencies.md
- .changeset/@graphql-yoga_urql-exchange-3501-dependencies.md
- .changeset/graphql-yoga-3501-dependencies.md
- .changeset/purple-lizards-divide.md
- packages/client/apollo-link/package.json
- packages/client/urql-exchange/package.json
- packages/graphiql/package.json
- packages/graphql-yoga/package.json
- packages/plugins/defer-stream/package.json
Aside from other important fixes, one notable fix is https://github.com/ardatan/graphql-tools/pull/6658.
> Update transport executors containing improvements and fixes

- packages/graphql-yoga/__integration-tests__/browser.spec.ts
Testing with timeouts is always flakey and should be avoided.
> Avoid timeouts when testing SSE subscriptions in browser

- .changeset/changelog1.md
- packages/plugins/apollo-usage-report/src/index.ts
If someone send GraphQL query without `operationName` in request body, we should try to get it from the `OperationDefinitionNode` after the query parsing is finished.
I added this logic to the `onParse` (`onParseEnd`) handler, but I'm not sure if all the logic of the `onEnveloped` handler should be moved to the `onParseEnd` handler?
- e.g. the `operationName` is missing if someone send request with body
```json
{
"query": "query TestQueryName{me{userAccount{id loginName}}}"
}
```
and the result in Apollo Studio metrics is: ❌ 
- if someone send request with body
```json
{
"query": "query TestQueryName{me{userAccount{id loginName}}}",
"operationName": "TestQueryName"
}
```
the result in Apollo Studio metrics is: ✅
> apollo-usage-report - get missing operationName from the OperationDefinitionNode

- .changeset/changelog.md
- packages/plugins/apollo-usage-report/src/index.ts
This PR removes option to set `clientName` and `clientVersion` as a static `string` in `ApolloUsageReportOptions`, because from "Apollo metrics" point of view it does not make sense.
It's related to PR https://github.com/dotansimha/graphql-yoga/pull/3448
> Remove option to set clientName and clientVersion as a static string

- CONTRIBUTING.md
This begins a contributing doc. Certainly something I expect to evolve. Let's keep it brief and to the point. We have a lot of repos at The Guild so, if there is common contributing guide content, perhaps that gets factored out into a single place that all other repo contrib guides can link to.
> chore: add contributing doc

- examples/hackernews/src/schema/base/resolvers/Link.ts
- examples/hackernews/src/schema/base/schema.graphql
- website/src/pages/tutorial/basic/08-graph-relations.mdx
- website/src/pages/tutorial/basic/11-setting-up-graphql-code-generator.mdx
I was thinking about this again and went back to the original type :)
But it was after I learned a lot from @n1ru4l and @eddeee888 and I've added many more comments about the comments return types and why we chose this, so I think overall it was worth the long trip...
> Tutorial - Update Link.comments return type

- .changeset/@graphql-yoga_plugin-apollo-usage-report-3549-dependencies.md
- .changeset/@graphql-yoga_plugin-apq-3549-dependencies.md
- .changeset/@graphql-yoga_plugin-persisted-operations-3549-dependencies.md
- .changeset/graphql-yoga-3549-dependencies.md
- packages/graphql-yoga/package.json
- packages/graphql-yoga/src/error.ts
- packages/graphql-yoga/src/index.ts
- packages/graphql-yoga/src/plugins/plugins.test.ts
- packages/graphql-yoga/src/plugins/request-validation/use-limit-batching.ts
- packages/graphql-yoga/src/plugins/result-processor/stringify.ts
- packages/graphql-yoga/src/server.ts
- packages/plugins/apollo-managed-federation/src/index.ts
- packages/plugins/apollo-usage-report/package.json
- packages/plugins/apq/package.json
- packages/plugins/defer-stream/src/validations/defer-stream-directive-label.ts
- packages/plugins/defer-stream/src/validations/defer-stream-directive-on-root-field.ts
- packages/plugins/defer-stream/src/validations/overlapping-fields-can-be-merged.ts
- packages/plugins/defer-stream/src/validations/stream-directive-on-list-field.ts
- packages/plugins/persisted-operations/package.json
- Bump dependencies
- Export helpers for Yoga plugins
- Reorganize exports and imports
- Remove unnecessary peer deps
Closes https://github.com/dotansimha/graphql-yoga/issues/3217
> Bump dependencies and export helpers

- .changeset/hip-oranges-argue.md
- packages/graphql-yoga/src/graphiql.html
> fix: update stylesheet link in graphiql.html (#3550)

- .changeset/@graphql-yoga_plugin-sofa-3559-dependencies.md
- .changeset/soft-turtles-deny.md
- packages/plugins/sofa/package.json
- packages/plugins/sofa/src/index.ts
- packages/plugins/sofa/tests/sofa.test.ts
- pnpm-lock.yaml
- website/src/pages/docs/features/sofa-api.mdx
Fix the issue when SOFA returns 404 response from error extensions returned by a resolver, it will cause the server to continue the request handling with Yoga but instead it should return the response with 404 and the body SOFA returns.
That line was causing a 404 response to continue with Yoga's handler;
https://github.com/dotansimha/graphql-yoga/pull/3559/files#diff-ede815ebc73ee3925e49864ba3ac573940f77e8542cf395ccbf405b284c006aeL120
As in this test case;
```ts
it('forwards error extensions correctly', async () => {
const yoga = createYoga({
schema: createSchema({
typeDefs: /* GraphQL */ `
type Query {
me: Account
}
type Account {
id: ID!
name: String!
}
`,
resolvers: {
Query: {
me: () => {
throw createGraphQLError('account not found', {
extensions: {
code: 'ACCOUNT_NOT_FOUND',
http: { …
```
> fix(sofa): respect error extensions in case of 404

- .changeset/@graphql-yoga_apollo-managed-federation-3567-dependencies.md
- .changeset/graphql-yoga-3567-dependencies.md
- packages/graphql-yoga/package.json
- packages/graphql-yoga/src/server.ts
- packages/plugins/apollo-managed-federation/package.json
- packages/plugins/apollo-managed-federation/src/index.ts
- pnpm-lock.yaml
- website/src/pages/docs/features/_meta.ts
- website/src/pages/docs/features/envelop-plugins.mdx
- website/src/pages/docs/features/explicit-resource-management.mdx
After the discussion with @n1ru4l ;
Some changes are done in `@whatwg-node/server`, so in order to configure the new feature (including the new hook);
- Allow to configure server adapter from Yoga options such as `disposeOnProcessTerminate`
- Allow to use the new hook
- Document `dispose` method, `onDispose` hook, `ctx.waitUntil` and everything related to the things related to the resource management and graceful shutdown
cc @EmrysMyrddin about https://github.com/graphql-hive/console/pull/6128
> New Explicit Resource Management docs and improvements

- .changeset/thirty-jokes-compare.md
- packages/graphql-yoga/src/index.ts
- packages/graphql-yoga/src/plugins/use-parser-and-validation-cache.ts
- packages/graphql-yoga/src/utils/create-lru-cache.ts
Mark `createLRUCache` utility as deprecated, and export it as `_createLRUCache` marking it as an
internal utility
> Mark `createLRUCache` as an internal utility

- .changeset/rich-goats-rescue.md
- package.json
- packages/plugins/jwt/package.json
- packages/plugins/jwt/src/__tests__/jwt.spec.ts
- packages/plugins/jwt/src/config.ts
- packages/plugins/jwt/src/index.ts
- packages/plugins/jwt/src/plugin.ts
- packages/plugins/jwt/src/utils.ts
- pnpm-lock.yaml
- website/src/pages/docs/features/jwt.mdx
- Support non-Yoga server implementations with Envelop hooks, so it works with GraphQL WS.
- Export `extractFromConnectionParams` helper to extract tokens from the connection params of the WebSocket connection
Fixes https://github.com/graphql-hive/gateway/issues/366
> enhance(jwt): `WebSockets` support

- .changeset/afraid-olives-attend.md
- .changeset/graphql-yoga-3620-dependencies.md
- packages/graphql-yoga/package.json
- pnpm-lock.yaml
https://security.snyk.io/vuln/SNYK-JS-DSET-7116691
> Bump dset dependency handling the CVE-2024-21529

- .changeset/tiny-hats-do.md
- packages/plugins/prometheus/__integration-tests__/graphql-ws.test.ts
- packages/plugins/prometheus/package.json
- packages/plugins/prometheus/src/index.ts
- pnpm-lock.yaml
Fixes https://github.com/dotansimha/graphql-yoga/issues/3374
Fixes https://github.com/graphql-hive/gateway/issues/450
Skip collecting Yoga/HTTP specific metrics in case of WS or any other usage of the Envelop instance of Yoga
> fix(prom): graphql-ws integration

- website/src/pages/docs/integrations/integration-with-koa.mdx
I saw that these docs were updated recently, and this is also something we were struggling with in one of our applications. I noticed that we do need to use `ctx.request`, but the documentation was a bit confusing - it mentioned:
> Make sure it is **not** `ctx.request` **not** `ctx.req`
(two negatives)
We currently use [koa-body](https://www.npmjs.com/package/koa-body#options), and by **default**, it does:
- `patchNode: false` =  not place parsed body in `ctx.req` (Node.js `IncomingMessage` type)
- `patchKoa: true` = does place parsed body in `ctx.request` (Koa's [Request](https://github.com/koajs/koa/blob/master/docs/api/request.md), abstraction of Node's request)
From the investigation, it's known that we must use the `ctx.request` object that does have the parsed body.
Without …
> fix: Update koa's integration guide for body parsing

- .changeset/funny-baboons-prove.md
- .changeset/tasty-seas-juggle.md
- packages/plugins/disable-introspection/src/index.ts
- packages/plugins/jwt/src/__tests__/jwt.spec.ts
- packages/plugins/jwt/src/config.ts
- packages/plugins/jwt/src/plugin.ts
- website/src/pages/docs/features/introspection.mdx
- website/src/pages/docs/features/jwt.mdx
Fixes https://github.com/dotansimha/graphql-yoga/discussions/3614 so you can combine JWT plugin with introspection plugin in this case.
```ts
import { useDisableIntrospection } from '@graphql-yoga/plugin-disable-introspection'
import { useJWT } from '@graphql-yoga/plugin-jwt'
const yoga = createYoga({
// ...
plugins: [
useJWT({
reject: {
missingToken: false,
invalidToken: false
}
}),
useDisableIntrospection({
disableIf(_req, ctx) {
// If there is no JWT token(unauthorized), disable introspection
if (!ctx.jwt) {
return true
}
return false
}
})
]
})
```
The following changes are needed;
JWT Plugin changes;
Ensure the JWT context has been added before any GraphQL Execution hooks when the plugin is used via Yoga
Introspection plugin changes;
Expose the server context as the second parameter, …
> fix(jwt/introspection): ability to disable introspection based on JWT result

- .changeset/stale-schools-tell.md
- packages/graphiql/src/YogaGraphiQL.tsx
- packages/graphql-yoga/__integration-tests__/browser.spec.ts
- pnpm-lock.yaml
Show deprecated input fields, arguments and all other input values in GraphiQL
Fixes https://github.com/graphql-hive/gateway/issues/535
> fix(graphiql): show input value deprecations

- .changeset/hungry-melons-admire.md
- packages/plugins/apollo-inline-trace/src/index.ts
- packages/plugins/apollo-usage-report/src/index.ts
Wait for setting schemaId to prevent race condition, previously it wasn't waiting so sometimes at the beginning, `Misformed trace, missing operation key or schema id` was thrown
> fix(apollo-usage-report): wait for hashing schema before preparing the report

- .changeset/friendly-actors-brake.md
- packages/graphql-yoga/__tests__/plugin-hooks.spec.ts
- packages/graphql-yoga/src/plugins/types.ts
- packages/graphql-yoga/src/server.ts
Now it is possible to replace or wrap the logic how `GraphQLParams` handled;
By default Yoga calls Envelop to handle the parameters, but now you can replace it with your own logic.
Closes https://github.com/dotansimha/graphql-yoga/pull/3734
Fixes YOGA-2
Example: Wrap the GraphQL handling pipeline in an `AsyncLocalStorage`
```ts
function myPlugin(): Plugin {
const context = new AsyncLocalStorage();
return {
onParams({ paramsHandler, setParamsHandler }) {
const store = { foo: 'bar' }
setParamsHandler(payload => context.run(store, paramsHandler, payload))
}
}
```
> feat: replace/wrap the logic `params` handled - `ParamsHandler`

- .changeset/grumpy-llamas-bake.md
- packages/plugins/response-cache/__tests__/response-cache.spec.ts
- packages/plugins/response-cache/src/index.ts
Ref GW-42
Fixes https://github.com/graphql-hive/gateway/issues/494
Now the WeakMap uses the `context` instead of the `request` correctly returning the operation ID for each operation in a batched request.
> Response caching for batched requests

- website/src/content/docs/integrations/integration-with-fastify.mdx
Upgraded doc to work with Fastify v5, according to this issue:
https://github.com/dotansimha/graphql-yoga/issues/3763
> Update integration-with-fastify.mdx for fastify v5

- .changeset/graphql-yoga-3672-dependencies.md
- .changeset/smooth-spoons-greet.md
- examples/error-handling/__integration-tests__/error-handling.spec.ts
- examples/graphql-armor/__integration-tests__/graphql-armor.spec.ts
- packages/graphql-yoga/__tests__/500.spec.ts
- packages/graphql-yoga/__tests__/batching.spec.ts
- packages/graphql-yoga/__tests__/error-masking.spec.ts
- packages/graphql-yoga/__tests__/graphql-over-http.spec.ts
- packages/graphql-yoga/__tests__/graphql-sse.spec.ts
- packages/graphql-yoga/__tests__/logging.spec.ts
- packages/graphql-yoga/__tests__/subscriptions.spec.ts
- packages/graphql-yoga/__tests__/validation-cache.spec.ts
- packages/graphql-yoga/package.json
- packages/graphql-yoga/src/error.ts
- packages/graphql-yoga/src/plugins/request-parser/post-json.ts
- packages/graphql-yoga/src/plugins/request-validation/use-check-graphql-query-params.ts
- packages/graphql-yoga/src/plugins/request-validation/use-http-validation-error.ts
- packages/graphql-yoga/src/plugins/request-validation/use-limit-batching.ts
- packages/graphql-yoga/src/plugins/request-validation/use-prevent-mutation-via-get.ts
- packages/graphql-yoga/src/utils/mask-error.ts
- pnpm-lock.yaml
Something like;
https://www.apollographql.com/docs/apollo-server/data/errors#built-in-error-codes
Related https://github.com/ardatan/graphql-tools/pull/6868
> feat: use `extensions.code` to specify errors

- .changeset/@graphql-yoga_nestjs-federation-3865-dependencies.md
- .changeset/@graphql-yoga_plugin-apollo-inline-trace-3865-dependencies.md
- .changeset/@graphql-yoga_plugin-prometheus-3865-dependencies.md
- .changeset/@graphql-yoga_plugin-response-cache-3865-dependencies.md
- .changeset/graphql-yoga-3865-dependencies.md
- import-map.json
- packages/graphql-yoga/CHANGELOG.md
- packages/graphql-yoga/__tests__/instruments.spec.ts
- packages/graphql-yoga/package.json
- packages/graphql-yoga/src/index.ts
- packages/graphql-yoga/src/plugins/types.ts
- packages/graphql-yoga/src/server.ts
- packages/nestjs-federation/package.json
- packages/plugins/apollo-inline-trace/package.json
- packages/plugins/apollo-managed-federation/package.json
- packages/plugins/apollo-usage-report/package.json
- packages/plugins/defer-stream/package.json
- packages/plugins/prometheus/package.json
- packages/plugins/response-cache/package.json
- packages/subscription/package.json
- pnpm-lock.yaml
- website/src/content/docs/features/envelop-plugins.mdx
Continue https://github.com/n1ru4l/envelop/pull/2486
> Rename instruments to instrumentation

- .changeset/deep-doodles-hang.md
- packages/graphql-yoga/__tests__/error-masking.spec.ts
- packages/graphql-yoga/src/utils/mask-error.ts
Related GW-297
Handle unexpected errors correctly
If it has a non GraphQL Error in `originalError`, consider it as an unexpected error (This was the same with the previous behavior but checking the original error logic wasn't working properly)
> fix: handle originally unexpected errors correctly

- examples/sveltekit/package.json
- package.json
- packages/graphql-yoga/package.json
- patches/jest-leak-detector@29.7.0.patch
- pnpm-lock.yaml
Jest v30 introduced a bug which prevent us from using `--detectLeaks` on Node 20. Running test with this option is hammering the CPU, to the point where the test fails to finish.
> fix(ci): downgrade jest to version 29

- .changeset/rotten-chicken-camp.md
- package.json
- packages/plugins/response-cache/__tests__/response-cache.spec.ts
- packages/plugins/response-cache/package.json
- packages/plugins/response-cache/src/index.ts
- packages/plugins/sofa/src/__tests__/sofa.spec.ts
- pnpm-lock.yaml
This PR fixes the type incompatibility between `Cache` type from Envelop and `Cache` type from Yoga.
There was 2 things that was wrong:
- The GraphQL response extension `responseCache` was marked as required, which is false (you can disable response cache metadata with `includeExtensionMetadata` option.
- The return type of `Cache.get` in Yoga disallows `null` values, while Envelop allows it. Based on code, Envelop is the correct one, as `null` and `undefined` are handled the same way.
I have marked this change as a patch since the types were actually wrong, but this can of course trigger errors in existing setup (since I'm making `responseCache` extension nullable). Should we mark it as a major because of this?
Related to #3048
Related to YOGA-78
> fix(response-cache): fix `cache` option type, fixing redis and cf-kv usage

- examples/deno/index.ts
- examples/deno/package.json
- examples/deno/test.ts
- import-map.json
- website/src/content/docs/integrations/integration-with-deno.mdx
- docs are hosted under .com
- Deno.serve stabilised a while back
- add imports w/o which example scripts wouldn't run
- stop using `--unstable` as it's been removed in v2 and isn't serving any significant purpose in examples
> chore: update Deno examples and references

- .eslintrc.json
- pnpm-lock.yaml
- website/next-env.d.ts
- website/next.config.ts
- website/package.json
- website/route-lockfile.txt
@renovate-bot don't upgrade Tailwind ever here, please.
This fixes the broken styles in the website.
As this happened because of a patch dependency bump, I'll add a simple screenshot test. I'm slowly becoming a Playwright-maxi.
> Downgrade Tailwind to 3.4.17 to fix the website
