README.md, examples/file-upload/README.md, examples/file-upload/index.ts, examples/file-upload/package.json, examples/file-upload/tsconfig.json, package.json, src/index.ts, src/types.ts, tsconfig.json, yarn.lock
Replaces #6.
Thanks a lot for the previous PR @jaydenseric. There were a couple of adjustments needed.
To make it easier for people to try it out without needing to spin up a full-fledged frontend, it would be great if there were a couple of curl commands you can run in your terminal.
@jaydenseric can you create another PR with a `curl` example in the `examples/file-upload/README.md`?
=> File uploads

src/index.ts
To do async processing, for example:  authentication
https://github.com/graphcool/graphql-yoga/issues/28#issuecomment-352234669
=> made async

examples/file-upload/package.json, examples/fullstack/server/package.json, examples/hello-world/package.json, examples/subscriptions/package.json
=> fix(example/hello-world): problem with version 0.0.1

src/index.ts
=> feat(subscription): expose withFilter

package.json, src/index.ts, yarn.lock
=> feat: use body-parser-graphql

README.md, src/index.ts, src/types.ts
BREAKING CHANGES: constructor and start options have changed
Closes #11, closes #16, closes #71
=> feat: new options structure and added apollo-server-options

package.json, yarn.lock
It doesn't seem to be used anywhere.
=> Remove `portfinder`.

src/lambda.ts
=> fix(GraphQLServerLambda): add null check for event headers

README.md
=> docs(readme): document fieldResolver option

src/index.ts
=> Fix uploads option behavior to conform docs

examples/apollo-engine/README.md, examples/custom-directives/README.md, examples/file-upload/README.md, examples/fullstack/README.md, examples/hello-world/README.md, examples/subscriptions/README.md
=> Fix bad git urls

README.md, src/index.ts, src/types.ts
https://github.com/graphcool/graphql-yoga/issues/210
=> #210 Adding support for HTTPS server option.

src/index.ts, src/types.ts
=> Allow port to be a string

src/types.ts
=> Add Response to types

examples/authentication/express-session/index.js, examples/authentication/express-session/package.json, examples/authentication/express-session/readme.md
This is an example on how users can use express-session with the graphql-yoga package.
=> Authentication: Express Session Example.

package.json, src/index.test.ts, tsconfig.json, yarn.lock
Be less cowboy. Test your code. At least a little.
🤠
- Added `ava` (chose it over jest/tape/etc as I saw graphcool was using it on some other project)
- Added `request-promise-native` to do outside-in test (if you prefer me using built-in http client I can look into doing that.. it's just my go-to request dep)
- Switched scripts to use yarn over `npm run` as you depend on yarn anyway and added at as a dev dep
- Added a `yarn watch` that runs any `watch:*` task (with help of `npm-run-all`)
=> test: Add ava and simple hello world integration test

examples/apollo-engine/package.json
Context: https://github.com/graphcool/graphql-yoga/pull/209#discussion_r176478619
cc @fabien0102
=> Upgrade graphql-yoga dependency in apollo-engine example

package.json, tsconfig.json
=> Fix `yarn watch` without breaking package.json

examples/mongodb/.babelrc, examples/mongodb/docker-compose.yml, examples/mongodb/package.json, examples/mongodb/readme.md, examples/mongodb/src/db/index.js, examples/mongodb/src/db/post.js, examples/mongodb/src/graphql/resolvers.js, examples/mongodb/src/graphql/schema.graphql, examples/mongodb/src/index.js
Fixes: #277 
Well, this is just an example on how to use MongoDB using GraphQL-YOGA.
=> MongoDB GraphQL-Yoga Example.

src/index.ts, src/types.ts
=> Added host name to HTTP Options

packages/graphql-yoga/__tests__/integration.spec.ts, packages/graphql-yoga/package.json, packages/graphql-yoga/src/index.ts, packages/graphql-yoga/src/types.ts, yarn.lock
Create a simple wrapper around `Fastify.inject` to help test graphql operations.
=> feat: testing util to simplify setup

README.md, package.json, website/package.json, website/routes.ts, yarn.lock
- fix: broken link
- chore: do no publish site
- docs: update readme
=> update readme and fix docs

.husky/pre-commit, package.json, packages/core/src/index.ts, packages/graphql-yoga/CHANGELOG.md, packages/graphql-yoga/__tests__/integration.spec.ts, packages/graphql-yoga/src/index.ts, packages/graphql-yoga/src/types.ts, website/tsconfig.json, yarn.lock
- style: run prettier
- build: setup pretty-quick
=> build: setup husky and pretty-quick

.changeset/rude-shirts-eat.md, .github/workflows/canary.yml, examples/express/package.json, examples/express/src/app.ts, examples/express/src/index.ts, examples/express/test/express.spec.ts, examples/express/tsconfig.json, examples/fastify/package.json, examples/fastify/src/app.ts, examples/fastify/src/index.ts, examples/fastify/test/fastify.spec.ts, examples/fastify/tsconfig.json, examples/fullstack/frontend/src/App.test.js, jest.config.js, package.json, packages/core/package.json, packages/core/src/index.ts, packages/graphql-yoga/__tests__/integration.spec.ts, packages/graphql-yoga/package.json, packages/graphql-yoga/src/index.ts, packages/graphql-yoga/src/types.ts, packages/graphql-yoga/test-utils/schema.ts, packages/handler/package.json, packages/handler/src/index.ts, yarn.lock
=> Drop Fastify in favor of Node HTTP

.changeset/pretty-boats-wonder.md, packages/graphql-yoga/src/index.ts
- feat: export everything in envelop core
- chore: add changeset
=> re-export envelop

.changeset/great-pumas-cheat.md, README.md, examples/defer-stream/src/index.ts, examples/express/src/app.ts, examples/fastify/src/app.ts, examples/hello-world/README.md, examples/subscriptions/src/index.ts, packages/cli/src/index.ts, packages/core/src/index.ts, packages/graphql-yoga/README.md, packages/graphql-yoga/__tests__/integration.spec.ts, packages/graphql-yoga/src/index.ts, packages/graphql-yoga/src/types.ts, packages/handler/src/index.ts, website/docs/extend-yoga/apollo-federation.mdx, website/docs/extend-yoga/envelop-plugins.mdx, website/docs/extend-yoga/file-uploads.mdx, website/docs/extend-yoga/graphiql.mdx, website/docs/extend-yoga/subscriptions.mdx, website/docs/integrations/integration-with-cf.mdx, website/docs/integrations/integration-with-deno.mdx, website/docs/integrations/integration-with-express.mdx, website/docs/integrations/integration-with-fastify.mdx, website/docs/integrations/integration-with-koa.mdx, website/docs/integrations/integration-with-nextjs.mdx, website/docs/migration/migration-from-express-graphql.mdx, website/docs/quick-start.mdx
- feat: rename createGraphQLServer to createServer
- chore: add changeset
=> rename create method

website/docs/extend-yoga/apollo-federation.mdx, website/docs/extend-yoga/envelop-plugins.mdx, website/docs/integrations/integration-with-cf.mdx, website/docs/integrations/integration-with-deno.mdx, website/docs/testing.mdx, website/routes.ts, website/src/pages/_app.tsx
- fix: get started button link
- docs: testing
- fix: sidebar
- fix: minor things
=> docs: testing

examples/sveltekit/src/routes/api/graphiql.ts, examples/sveltekit/src/routes/api/graphql.ts, website/docs/integrations/integration-with-sveltekit.mdx
=> sveltekit: update doc and example to refect createServer update

.changeset/eleven-foxes-knock.md, benchmark/hello-world/start-server.js, examples/express/src/app.ts, examples/express/src/index.ts, examples/express/test/express.spec.ts, examples/fastify/src/app.ts, examples/fastify/src/index.ts, examples/hello-world/index.js, packages/core/src/index.ts, packages/graphql-yoga/__tests__/integration.spec.ts, packages/graphql-yoga/src/index.ts, packages/graphql-yoga/src/types.ts, website/docs/integrations/integration-with-fastify.mdx
option for introspection and masking errors
=> control over intropection and error options

.changeset/fast-chicken-turn.md, packages/core/src/index.ts, packages/graphql-yoga/src/index.ts, packages/handler/src/index.ts
- feat: export render graphiql
- chore: add changeset
=> export renderGraphiQL function

examples/sveltekit/package.json, examples/sveltekit/src/lib/graphql/yogaHandler.ts, package.json, website/docs/integrations/integration-with-sveltekit.mdx, yarn.lock
Following the Breaking changes of SvelteKit:
https://github.com/sveltejs/kit/blob/master/packages/kit/CHANGELOG.md#100-next208
I updated params
=> Fix SvelteKit Breaking changes .208

.changeset/silly-cougars-design.md, packages/core/src/index.ts, packages/graphql-yoga/__tests__/integration.spec.ts, website/docs/migration/migration-from-apollo-server.mdx
better naming: replace `introspection` option name with `disableIntrospection`
=> Clearer introspection property name

examples/fastify/src/app.ts, examples/fastify/tsconfig.json, packages/handler/src/getGraphQLParameters.ts
Modularize the request parsers.
First small step regarding https://www.figma.com/file/DpMLbOyBM2hL9RyMojbVYA/GraphQL-Yoga-Plugin-System
=> getGraphQLParameters refactor

examples/sveltekit/src/routes/api/graphql.ts, packages/common/src/server.ts, website/docs/features/error-masking.mdx, website/docs/integrations/integration-with-sveltekit.mdx
=> Update/doc on maskedErrors & JSDoc

.changeset/brave-cooks-fail.md, .changeset/cool-ants-grin.md, .changeset/light-dancers-lick.md, .changeset/wicked-squids-deliver.md, .vscode/settings.json, packages/common/package.json, packages/graphql-yoga/package.json, packages/node/__tests__/integration.spec.ts, packages/node/package.json, packages/node/src/index.ts, packages/subscription/package.json, yarn.lock
- fix(node): use localhost instead of 0.0.0.0 on Windows
- feat(node): add getServerUrl that returns expected full GraphQL API URL
=> Some improvements on Node package

packages/graphiql/README.md, packages/graphiql/src/YogaGraphiQL.tsx, packages/graphiql/src/dark-mode.css, packages/graphiql/src/declarations.d.ts, yarn.lock
Here is how it looks like: 
- I used colors starting with graphql & yoga logo. With a few things in mind
- Results are in greenish
- Variables are a bit flashy to pop out
- types are orangy
- I added explorer colors & typings
- I added a few css that was not present before
- I synchronized Explorer / Doc / Middle colors.
You can change each colors, but I think that it's a base to start.
=> colors for dark mode

packages/graphiql/README.md, packages/graphiql/src/YogaGraphiQL.tsx, packages/graphiql/src/dark-mode.css, packages/graphiql/src/declarations.d.ts, patches/graphiql-explorer+0.9.0.patch, yarn.lock
=> Dark Theme for YogaGraphiQL

website/docs/features/apollo-federation.mdx, website/docs/migration/migration-from-apollo-server.mdx, website/docs/quick-start.mdx
- doc: update recommendation
- docs: fix examples
=> fix docs example

renovate.json, scripts/vercel-ignore-build-step.sh
- update website settings: https://vercel.com/theguild/graphql-yoga/settings/git
=> chore(renovate): shared config + vercel skip build

.changeset/wild-paws-design.md, examples/error-handling/package.json, package.json, packages/common/package.json, packages/common/src/getResponse.ts, packages/node/package.json, yarn.lock
=> fix(common): bump cross-undici-fetch and pass encoding header for wider support

.changeset/four-timers-sip.md, examples/subscriptions/package.json, packages/graphiql/package.json, packages/graphiql/src/YogaGraphiQL.tsx, packages/node/__tests__/integration.spec.ts, yarn.lock
This PR will also validate `defaultQuery` option is working fine.
=> feat(graphiql): use query search param for default query

packages/common/src/server.ts, packages/common/src/types.ts
=> Expose extensions sent by the client in the initial context

.changeset/cold-readers-begin.md, examples/nextjs/pages/api/graphql.ts, packages/common/__tests__/logging.test.ts, packages/common/package.json, packages/common/src/index.ts, packages/common/src/logger.ts, packages/common/src/server.ts, packages/common/src/types.ts, packages/node/package.json, packages/node/src/index.ts, packages/node/src/types.ts, yarn.lock
=> remove pino for Node and use a cross-platform simple logger

examples/subscriptions/.gitignore, examples/subscriptions/codegen.yml, examples/subscriptions/package.json, examples/subscriptions/src/index.ts, yarn.lock
=> setup codegen for subscriptions example

README.md, examples/deno/index.ts, website/docs/features/apollo-federation.mdx, website/docs/integrations/integration-with-aws-lambda.mdx, website/docs/integrations/integration-with-cloudflare-workers.mdx, website/docs/integrations/integration-with-deno.mdx, website/docs/integrations/integration-with-express.mdx, website/docs/integrations/integration-with-fastify.mdx, website/docs/integrations/integration-with-koa.mdx, website/docs/integrations/integration-with-nextjs.mdx, website/docs/integrations/integration-with-sveltekit.mdx, website/docs/migration/migration-from-apollo-server.mdx, website/docs/migration/migration-from-express-graphql.mdx, website/docs/quick-start.mdx, website/tutorial/basic/03-graphql-server.mdx
Remove occurrences of `@beta` tag
=> doc: update install instructions for 2.0

LICENSE, README.md
- update license
- update readme
=> update readme and license

.github/ISSUE_TEMPLATE/bug_report.md, examples/issue-template/package.json, examples/issue-template/src/main.ts, examples/issue-template/tsconfig.json
The link points to:
https://stackblitz.com/github/dotansimha/graphql-yoga/tree/master/examples/issue-template
This ensures that the user is always using the latest versions 🤔
=> chore: stackblitz issue template

examples/file-upload-nexus/index.ts, examples/file-upload-nexus/package.json, examples/file-upload-nexus/tsconfig.json, website/docs/features/file-uploads.mdx
see https://github.com/dotansimha/graphql-yoga/discussions/1030#discussioncomment-2490827
=> GraphQL Nexus file upload doc example

website/tutorial/basic/00-introduction.mdx, website/tutorial/basic/01-project-setup.mdx, website/tutorial/basic/03-graphql-server.mdx, website/tutorial/basic/04-a-simple-query.mdx
Changes:
- Comment TODO 
- Simple Query - Screenshot - Update PNG path 
-  Text correction
=> Basic Yoga tutorial

.changeset/proud-walls-glow.md, packages/common/src/server.ts, packages/common/type-api-check.ts, packages/node/src/index.ts, website/docs/features/graphiql.mdx
=> feat: allow boolean for graphiql

.github/workflows/website-integrity.yml, package.json, website/.gitignore, website/next-sitemap.js, website/package.json, website/route-lockfile.txt, website/scripts/sitemap-ci.ts, yarn.lock
please have a look and tell me what you think.
=> chore: add route lockfile ci action

README.md, website/tutorial/basic/01-project-setup.mdx, website/tutorial/basic/03-graphql-server.mdx, website/tutorial/basic/06-adding-a-database.mdx
* Use correct `--save-exact` flag
* Remove todo placeholder
* Update LICENSE url to go to `https://raw.githubusercontent.com/dotansimha/graphql-yoga/master/LICENSE` not Apollo
=> docs(tutorial): Use correct NPM save-exact flag

examples/file-upload-nextjs-pothos/README.md, examples/file-upload-nextjs-pothos/next-env.d.ts, examples/file-upload-nextjs-pothos/package.json, examples/file-upload-nextjs-pothos/pages/api/graphql.ts, examples/file-upload-nextjs-pothos/tsconfig.json, examples/file-upload-nexus/index.ts, yarn.lock
This PR adds example with `Next.js`, `Pothos`, and file uploads.
=> example: add file upload with Next.js and Pothos GraphQL

.changeset/lucky-trains-sit.md, .changeset/small-bottles-compete.md, .vscode/settings.json, examples/file-upload-nextjs-pothos/package.json, package.json, packages/common/.gitignore, packages/common/package.json, packages/common/scripts/generate-graphiql-html.js, packages/common/src/encodeString.ts, packages/common/src/graphiql.html, packages/common/src/graphiql.ts, packages/common/src/logger.ts, packages/common/src/server.ts, yarn.lock
Not sure it is worth.
Less than 200 kb for CF Workers etc; (didn't put current one because bundlephobia is down right now)
=> Even smaller bundle size

.changeset/tidy-moose-sparkle.md, packages/common/__tests__/logging.test.ts, packages/common/src/logger.ts, packages/common/src/server.ts, packages/node/src/index.ts
=> Improve Log Messages

website/docs/migration/migration-from-yoga-v1.mdx
closes https://github.com/dotansimha/graphql-yoga/issues/1169
=> docs: document schema file v1 to v2 migration

website/docs/migration/migration-from-yoga-v1.mdx
closes https://github.com/dotansimha/graphql-yoga/issues/1173
=> docs: document migration path for schema directives for yoga v1 users

package.json, packages/graphiql/package.json, patches/graphiql+1.8.8.patch, yarn.lock
`@graphql-tools/url-loader` introduced a breaking change within version `"7.9.13"`.
=> feat: upgrade graphiql and graphql-tools/url-loader

.changeset/giant-fishes-deliver.md, packages/common/package.json, packages/node/package.json, yarn.lock
=> chore: remove @envelop/disable-introspection plugin

website/docs/features/context.mdx
=> docs: fix envelop plugins link

website/tutorial/basic/02-getting-started.mdx, website/tutorial/basic/07-connecting-server-and-database.mdx, website/tutorial/basic/08-graph-relations.mdx, website/tutorial/basic/09-error-handling.mdx, website/tutorial/basic/11-summary.mdx
Hi there :)
Just finished reading through the tutorial and noticed some spelling errors, so thought I'd contribute and help fix them.
=> Fixes spelling mistakes in tutorial

.changeset/curly-sheep-own.md, README.md, packages/common/src/plugins/requestParser/GET.ts, packages/common/src/plugins/requestParser/POSTFormUrlEncoded.ts, packages/common/src/plugins/requestParser/POSTGraphQLString.ts, packages/common/src/plugins/requestParser/POSTJson.ts, packages/common/src/plugins/requestParser/POSTMultipart.ts, packages/common/src/plugins/requestParser/utils.ts, packages/common/src/server.ts, packages/node/__tests__/integration.spec.ts
Related https://github.com/dotansimha/graphql-yoga/issues/1237
=> Support more request body types

.changeset/lazy-insects-dance.md, packages/node/src/index.ts
closes https://github.com/dotansimha/graphql-yoga/issues/1251
=> feat: export node types

.github/workflows/deployment-e2e.yml, .github/workflows/website-integrity.yml, e2e/index.ts, e2e/package.json, e2e/tests/aws-lambda.ts, e2e/tests/azure-function.ts, e2e/tests/cf-worker.ts, e2e/tests/vercel.ts, e2e/tsconfig.json, e2e/utils.ts, examples/fastify/__tests__/fastify.spec.ts, examples/fastify/src/app.ts, website/docs/features/file-uploads.mdx, website/docs/integrations/integration-with-fastify.mdx, yarn.lock
=> Update docs and examples for file uploads and fastify integration

examples/fastify-modules/package.json, examples/fastify-modules/src/app.ts, examples/fastify-modules/src/modules/basic/providers.ts, examples/fastify-modules/src/modules/basic/resolvers.ts, examples/fastify/package.json, examples/fastify/src/app.ts, website/docs/integrations/integration-with-fastify.mdx
=> Update docs and examples for Fastify v4

.changeset/thick-coats-tell.md, packages/common/src/plugins/useCORS.ts
=> Remove 'Server: GraphQL Yoga' header from the response

e2e/package.json, yarn.lock
Reverts dotansimha/graphql-yoga#1296
=> Revert "fix(deps): update dependency typescript to v4.7.4"

.github/workflows/algolia-integrity.yml, .github/workflows/website-integrity.yml, website/docs/quick-start.mdx
@n1ru4l I will go over all our repos to see if both Algolia and Website integrity scripts need fixing :shipit:
=> chore(ci): fix algolia script git issue

.changeset/silver-peas-admire.md, packages/common/src/plugins/requestValidation/useCheckGraphQLQueryParam.ts, packages/node/__tests__/integration.spec.ts
=> Descriptive Error Message if `GraphQLParams.query` is not a string

renovate.json
We want dependency updates in the `v3` branch.
=> chore: add v3 branch as renovate base branch

website/docs/features/file-uploads.mdx
adding missing schema type definition for saveFile mutation:)
=> docs: update file upload example

website/tutorial/basic/01-project-setup.mdx
project entrypoint: index.ts -> main.ts
=> docs: fix typo

website/v3/docs/features/error-masking.mdx
closes [#1327](https://github.com/dotansimha/graphql-yoga/issues/1327)
=> docs: document how the default HTTP status code can be altered

website/routes.ts, website/v3/docs/comparison.mdx, website/v3/docs/migration/migration-from-apollo-server.mdx
____
Closes https://github.com/dotansimha/graphql-yoga/issues/1026
=> docs: comparison with helix and apollo-server

examples/graphql-armor/README.md, examples/graphql-armor/package.json, examples/graphql-armor/src/main.ts, examples/graphql-armor/tsconfig.json, yarn.lock
Add an example for GraphQL Armor, compatible with Yoga v2.
=> example: add graphql-armor

.changeset/old-cycles-trade.md, packages/common/src/plugins/requestParser/POSTJson.ts, packages/node/__tests__/integration.spec.ts, yarn.lock
This PR reverts the breaking change introduced in 2.8.0(minor release)
=> fix(common): accept POST requests as JSON by default again

.changeset/mean-clouds-appear.md, packages/common/__tests__/plugins.test.ts, packages/common/src/server.ts
Related the issue in https://github.com/Escape-Technologies/graphql-armor/pull/113
=> Respect Envelop's OnPluginInit's addPlugin method

.changeset/healthy-hornets-do.md, packages/common/src/plugins/useCORS.ts
Fixes https://github.com/dotansimha/graphql-yoga/issues/1657
=> fix(cors): add content-length: 0 header if 204 is returned by OPTIONS request

website/src/pages/v3/comparison.mdx
=> docs: fix link

examples/file-upload-nextjs-pothos/__integration-tests__/file-upload-nextjs-pothos.spec.ts, examples/file-upload-nextjs-pothos/pages/api/graphql.ts, examples/file-upload-nextjs-pothos/schema.ts
=> test: file-upload-nextjs-pothos example

examples/node-ts/__integration-tests__/node-ts.spec.ts, examples/node-ts/package.json, examples/node-ts/src/index.ts, examples/node-ts/src/yoga.ts, examples/node-ts/tsconfig.json
=> Simple Node with TypeScript example

website/src/pages/v3/features/parsing-and-validation-caching.mdx
=> Documentation for parsing and validation caching

website/src/pages/v3/features/debugging.mdx
=> Debugging documentation

examples/hackernews/__integration-tests__/hackernews.spec.ts, examples/hackernews/__integration-tests__/prisma__migrate.d.ts, examples/hackernews/package.json, yarn.lock
=> Integration tests for hackernews example

website/src/pages/v3/comparison.mdx
Fixed couple of bad links on page: https://www.the-guild.dev/graphql/yoga-server/v3/comparison
=> docs: fix links

yarn.lock
for some werid reason it messed it up in last PR #1903
=> sycn lockfile

website/src/pages/v3/comparison.mdx
I've also added a link to a benchmark repo, even though I know it uses old Yoga for now (we'll get to it later)
=> Adding express-graphql comparison

.changeset/brown-steaks-explode.md, packages/graphiql/src/YogaGraphiQL.tsx
=> Dedent GraphiQL placeholder text

.changeset/hot-carrots-live.md, packages/graphql-yoga/src/landing-page.html
Closes #2056, eases up the styles for better performance and fixes documentation + tutorial links.
Looks like this now (not much changed):
=> Simplify landing page and fix links

website/src/pages/v3/features/context.mdx
structure for context object changed a little
=> docs: update context

packages/graphql-yoga/__tests__/500.spec.ts, packages/graphql-yoga/__tests__/error-masking.spec.ts, packages/graphql-yoga/__tests__/graphql-over-http.spec.ts, packages/graphql-yoga/src/error.ts, packages/graphql-yoga/src/plugins/resultProcessor/regular.ts, packages/graphql-yoga/src/plugins/resultProcessor/stringify.ts, packages/graphql-yoga/src/utils/yoga-default-format-error.ts
see https://github.com/graphql/graphql-over-http/blob/main/spec/GraphQLOverHTTP.md#applicationgraphql-responsejson
=> add tests for graphql over http specification

website/src/pages/v3/features/_meta.json, website/src/pages/v3/features/schema.mdx
closes https://github.com/dotansimha/graphql-yoga/issues/1886
=> docs: schema + conditional schema

.changeset/thin-rings-buy.md, packages/graphql-yoga/src/index.ts
Reverts dotansimha/graphql-yoga#2061
=> Revert "chore: re-export specific things from @envelop/core"

website/src/pages/docs/features/subscriptions.mdx
I followed the subscription guide and found some errors.
=> Fix typos in subscriptions.mdx

.changeset/unlucky-wasps-play.md, examples/pothos/package.json, examples/pothos/tsconfig.json, packages/graphql-yoga/package.json, packages/graphql-yoga/src/plugins/useReadinessCheck.ts, pnpm-lock.yaml
Fixes https://github.com/dotansimha/graphql-yoga/issues/2123
=> fix: bump @whatwg-node/server to fix webworker/dom conflict issue

.changeset/chilled-geese-clap.md, packages/graphql-yoga/__tests__/http-extensions.spec.ts, packages/graphql-yoga/src/error.ts, packages/graphql-yoga/src/plugins/requestParser/POSTJson.ts, packages/graphql-yoga/src/plugins/requestValidation/useCheckGraphQLQueryParams.ts, packages/graphql-yoga/src/plugins/requestValidation/useHTTPValidationError.ts, packages/graphql-yoga/src/plugins/requestValidation/usePreventMutationViaGET.ts, packages/graphql-yoga/src/plugins/resultProcessor/regular.ts
=> fix: allow user to set a status code even if content-type is application/json

.changeset/lemon-crabs-vanish.md, .changeset/serious-maps-double.md, packages/graphql-yoga/__tests__/recipes.spec.ts, packages/graphql-yoga/src/plugins/requestValidation/useCheckGraphQLQueryParams.ts
Alternative for https://github.com/dotansimha/graphql-yoga/pull/2124
=> test: add recipe for top-level id parameter

.changeset/bright-mirrors-exercise.md, packages/graphql-yoga/src/index.ts
https://github.com/kamilkisiela/graphql-hive/actions/runs/3546590035/jobs/5955834987#step:8:389
=> fix: revert the breaking change by exporting `useErrorHandler` again

.changeset/stale-parents-call.md, packages/graphql-yoga/src/error.ts, packages/graphql-yoga/src/plugins/plugins.test.ts, packages/graphql-yoga/src/plugins/requestValidation/useCheckGraphQLQueryParams.ts, packages/graphql-yoga/src/plugins/requestValidation/useCheckMethodForGraphQL.ts, packages/graphql-yoga/src/plugins/requestValidation/useHTTPValidationError.ts, packages/graphql-yoga/src/plugins/requestValidation/useLimitBatching.ts, packages/graphql-yoga/src/plugins/requestValidation/usePreventMutationViaGET.ts, packages/graphql-yoga/src/plugins/resultProcessor/stringify.ts, packages/graphql-yoga/src/plugins/useSchema.ts, packages/graphql-yoga/src/plugins/useUnhandledRoute.ts
Fixes https://github.com/dotansimha/graphql-yoga/issues/2174
=> fix: add missing `.js` extension to type imports

pnpm-lock.yaml, website/package.json
Signed-off-by: Tuval Simha <tuval.simha@gmail.com>
=> Website: update guild/component

.changeset/@graphql-yoga_apollo-link-2266-dependencies.md, .changeset/@graphql-yoga_graphiql-2266-dependencies.md, .changeset/@graphql-yoga_plugin-apollo-inline-trace-2266-dependencies.md, .changeset/@graphql-yoga_plugin-apq-2266-dependencies.md, .changeset/@graphql-yoga_urql-exchange-2266-dependencies.md, .changeset/calm-jars-draw.md, .changeset/graphql-yoga-2266-dependencies.md, examples/bun/package.json, examples/error-handling/package.json, packages/graphql-yoga/__tests__/requests.spec.ts, packages/graphql-yoga/package.json, packages/graphql-yoga/src/plugins/useGraphiQL.ts, packages/graphql-yoga/src/plugins/useHealthCheck.ts, packages/graphql-yoga/src/plugins/useReadinessCheck.ts, packages/graphql-yoga/src/plugins/useUnhandledRoute.ts, packages/graphql-yoga/src/server.ts, packages/plugins/apollo-inline-trace/package.json, packages/plugins/apq/package.json, packages/plugins/defer-stream/package.json, pnpm-lock.yaml
Fixes https://github.com/dotansimha/graphql-yoga/issues/2132
=> Allow URL patterns in `graphqlEndpoint`

examples/uwebsockets/__integration-tests__/uwebsockets.test.ts, examples/uwebsockets/package.json, examples/uwebsockets/src/app.ts, examples/uwebsockets/src/index.ts, examples/uwebsockets/tsconfig.json, jest.config.js, pnpm-lock.yaml, website/src/pages/docs/integrations/_meta.json, website/src/pages/docs/integrations/integration-with-uwebsockets.mdx
Closes https://github.com/dotansimha/graphql-yoga/issues/2286
=> Example with uWebSockets.js

.changeset/eighty-pigs-know.md, packages/subscription/src/operator/filter.spec.ts, packages/subscription/src/operator/filter.ts
Closes https://github.com/dotansimha/graphql-yoga/issues/2290
=> feat: support returning a Promise from the filter utility function

website/src/pages/docs/features/subscriptions.mdx
Closes https://github.com/the-guild-org/website/issues/1037
=> docs: correct graphql-sse and graphql-ws example links

.changeset/dull-pots-melt.md, packages/graphql-yoga/__tests__/http-extensions.spec.ts, packages/graphql-yoga/__tests__/requests.spec.ts, packages/graphql-yoga/src/plugins/resultProcessor/stringify.ts
=> fix: omit only internals in result errors when serialising result

website/src/pages/docs/features/persisted-operations.mdx
Only merge after https://github.com/dotansimha/graphql-code-generator/pull/8881 got merged.
=> docs: recommend client preset for extracting persisted operations

.changeset/@graphql-yoga_apollo-link-2379-dependencies.md, .changeset/@graphql-yoga_urql-exchange-2379-dependencies.md, packages/client/apollo-link/package.json, packages/client/urql-exchange/package.json, pnpm-lock.yaml, website/src/pages/docs/features/testing.mdx
- bump package versions and remove exact version pinning
- feat: update guide
=> testing docs + bump package versions and remove exact version pinning

.changeset/big-planes-doubt.md, .changeset/graphql-yoga-2393-dependencies.md, packages/graphql-yoga/__integration-tests__/incremental-delivery.spec.ts, packages/graphql-yoga/__tests__/validation-cache.spec.ts, packages/graphql-yoga/package.json, packages/graphql-yoga/src/plugins/useParserAndValidationCache.ts, packages/graphql-yoga/src/server.ts, packages/graphql-yoga/src/utils/create-lru-cache.ts, packages/plugins/graphql-sse/src/index.ts, pnpm-lock.yaml
Closes https://github.com/dotansimha/graphql-yoga/pull/2199
=> Decrease request latency by improving the validation and parser cache algorithm

packages/graphql-yoga/__tests__/subscriptions.spec.ts, packages/graphql-yoga/src/plugins/resultProcessor/push.ts
=> Test and make sure SSE pings are issued

.changeset/graphql-yoga-2470-dependencies.md, .changeset/mean-kings-grin.md, examples/response-cache/package.json, packages/graphql-yoga/package.json, pnpm-lock.yaml
to verify that tests should fail.
=> bump envelop/validation-cache

website/src/pages/tutorial/advanced/02-subscriptions.mdx
typo
or we could use just Error
=> docs: update 02-subscriptions.mdx

.github/workflows/ci.yml
https://github.com/apollographql/federation-subgraph-compatibility/issues/14
=> Use Apollo's Federation compatibility checker action

examples/hapi/__integration-tests__/hapi.spec.ts, examples/hapi/package.json, examples/hapi/src/app.ts, examples/hapi/src/index.ts, examples/hapi/tsconfig.json, pnpm-lock.yaml, website/src/pages/docs/integrations/_meta.json, website/src/pages/docs/integrations/integration-with-hapi.mdx
=> Hapi example

.changeset/tricky-actors-pay.md, packages/plugins/response-cache/__tests__/response-cache.spec.ts, packages/plugins/response-cache/src/index.ts
Fixes https://github.com/dotansimha/graphql-yoga/issues/2498
=> fix(response-cache): `enabled` flag

website/src/pages/docs/features/context.mdx
Signed-off-by: Tuval <tuval.simha@gmail.com>
=> GraphQL Context

website/src/pages/docs/features/introspection.mdx
Hey, I've added more documentation for GQL armor with a back-link to the plugins documentation.
=> Add more docs about GQL armor

.changeset/@graphql-yoga_apollo-link-2686-dependencies.md, .changeset/@graphql-yoga_plugin-apollo-inline-trace-2686-dependencies.md, .changeset/@graphql-yoga_plugin-apq-2686-dependencies.md, .changeset/@graphql-yoga_plugin-defer-stream-2686-dependencies.md, .changeset/@graphql-yoga_plugin-sofa-2686-dependencies.md, .changeset/@graphql-yoga_urql-exchange-2686-dependencies.md, .changeset/graphql-yoga-2686-dependencies.md, .changeset/thin-worms-shout.md, packages/client/apollo-link/package.json, packages/client/urql-exchange/package.json, packages/graphql-yoga/__tests__/subscriptions.spec.ts, packages/graphql-yoga/package.json, packages/graphql-yoga/src/server.ts, packages/plugins/apollo-inline-trace/package.json, packages/plugins/apq/package.json, packages/plugins/defer-stream/package.json, packages/plugins/sofa/package.json, pnpm-lock.yaml
Closes https://github.com/dotansimha/graphql-yoga/issues/2685
=> fix: handle subscription source error

.github/workflows/algolia-publish.yml, .github/workflows/website.yml
@dotansimha please make sure to remove all ALGOLIA-related secrets, except `ALGOLIA_ADMIN_API_KEY`
=> Algolia cleanup

packages/graphql-yoga/README.md
Fixes #2704
Given that there was already a Contributing section in the README, I've added to this rather than create a separate CONTRIBUTING.md - but if we'd prefer move it all out to a separate one I can do this.
=> Add contributing instructions

website/src/pages/tutorial/basic/04-a-simple-query.mdx
Signed-off-by: TuvalSimha <tuval.simha@gmail.com>
=> SEO: add title keyword

.changeset/proud-oranges-warn.md, packages/graphql-yoga/__tests__/schema.spec.ts, packages/graphql-yoga/src/plugins/useParserAndValidationCache.ts
small edge-case that we missed
=> fix: validation caching schema check

website/src/pages/docs/features/automatic-persisted-queries.mdx, website/src/pages/docs/features/envelop-plugins.mdx
I cant run formatting rn. On train without roaming, need to run pnpm install first and data plan is hella expensive lol
=> improve documentation around plugins

.changeset/graphql-yoga-2726-dependencies.md, .changeset/respect-tojson.md, packages/graphql-yoga/__tests__/http-extensions.spec.ts, packages/graphql-yoga/src/plugins/resultProcessor/stringify.ts
Fixes https://github.com/dotansimha/graphql-yoga/issues/2708
=> Respect toJSON in the thrown errors

examples/gcp-cloud-run/Dockerfile, examples/gcp-cloud-run/package.json, examples/gcp-cloud-run/src/index.js, pnpm-lock.yaml, website/src/pages/docs/integrations/integration-with-gcp-cloud-run.mdx
This PR adds a guide to deploy Yoga to Google Cloud Run and an linked example.
fixes #1153
=> Add an example for GCP Cloud Run

.changeset/quick-onions-joke.md, .changeset/rude-buttons-speak.md, examples/fastify/__integration-tests__/fastify.spec.ts, examples/generic-auth/__integration-tests__/generic-auth.spec.ts, examples/hapi/__integration-tests__/hapi.spec.ts, examples/node-ts/__integration-tests__/node-ts.spec.ts, examples/pothos/__integration-tests__/pothos.spec.ts, packages/graphiql/src/YogaGraphiQL.tsx, packages/graphql-yoga/__integration-tests__/browser.spec.ts, packages/graphql-yoga/__integration-tests__/incremental-delivery.spec.ts, packages/graphql-yoga/__tests__/graphql-sse.spec.ts, packages/graphql-yoga/__tests__/subscriptions.spec.ts, packages/graphql-yoga/src/plugins/resultProcessor/sse.ts, packages/graphql-yoga/src/plugins/useResultProcessor.ts, packages/graphql-yoga/src/server.ts, packages/nestjs/__tests__/subscriptions.spec.ts, website/src/pages/docs/features/subscriptions.mdx, website/src/pages/docs/migration/migration-from-yoga-v3.mdx
https://github.com/graphql/graphql-over-http/blob/main/rfcs/GraphQLOverSSE.md#distinct-connections-mode
=> [v4] Subscriptions use GraphQL over SSE "distinct connections mode"

website/src/pages/_meta.json, website/src/pages/changelog.md
=> add changelog to website

examples/sofa/__integration-tests__/sofa.spec.ts
Fixes some test that have broken the CI
=> fix expected sofa content-type header containing charset on node 16

.changeset/@graphql-yoga_plugin-apollo-inline-trace-2896-dependencies.md, .changeset/graphql-yoga-2896-dependencies.md, examples/cloudflare-modules/package.json, examples/error-handling/package.json, examples/file-upload-nextjs-pothos/package.json, examples/file-upload-nexus/package.json, examples/generic-auth/package.json, examples/hapi/package.json, examples/response-cache/package.json, examples/service-worker/package.json, examples/uwebsockets/package.json, package.json, packages/graphql-yoga/__tests__/requests.spec.ts, packages/graphql-yoga/package.json, packages/nestjs/package.json, packages/plugins/apollo-inline-trace/package.json, packages/plugins/defer-stream/package.json, pnpm-lock.yaml
Closes https://github.com/dotansimha/graphql-yoga/pull/2889
=> bump whatwg node

website/src/pages/docs/integrations/integration-with-sveltekit.mdx
=> update doc for usage of v4 with sveltekit

jest.config.js
Closes #2956
https://github.com/jestjs/jest/issues/14305
=> Disable prettier for jest

.changeset/pretty-drinks-behave.md, packages/graphiql/src/YogaGraphiQL.tsx
=> Use correct subscriptions endpoint in Yoga GraphiQL

.changeset/three-rabbits-exercise.md, packages/event-target/redis-event-target/__tests__/serializer.spec.ts, packages/event-target/redis-event-target/src/index.ts, website/src/pages/docs/features/subscriptions.mdx
It would for example allow using `superjson` instead of the default JSON implementation.
=> feat: allow custom serialize/deserialize redis messages

website/src/pages/docs/integrations/integration-with-uwebsockets.mdx
The `.listen()` method was missing
=> Fixed the basic example of integration of µWebSockets.js

.changeset/weak-trees-grow.md, examples/fastify/__integration-tests__/fastify.spec.ts, examples/generic-auth/__integration-tests__/generic-auth.spec.ts, examples/hapi/__integration-tests__/hapi.spec.ts, examples/node-ts/__integration-tests__/node-ts.spec.ts, examples/pothos/__integration-tests__/pothos.spec.ts, packages/graphql-yoga/__integration-tests__/browser.spec.ts, packages/graphql-yoga/__integration-tests__/incremental-delivery.spec.ts, packages/graphql-yoga/__tests__/graphql-sse.spec.ts, packages/graphql-yoga/__tests__/subscriptions.spec.ts, packages/graphql-yoga/src/plugins/result-processor/sse.ts, packages/nestjs/__tests__/subscriptions.spec.ts
This is required for `EventSource` to properly handle event source stream closures.
See https://github.com/enisdenjo/graphql-sse/commit/80cf75b5952d1a065c95bdbd6a74304c90dbe2c5
=> send empty data for complete event on sse stream

website/src/pages/docs/features/response-caching.mdx
This Pull requests fixes the issue described at #3141 and extra typo fixes.
=> Corrected incorrect code snippet in response caching guide

.changeset/fair-walls-repair.md, packages/graphql-yoga/src/plugins/use-execution-cancellation.ts
closes https://github.com/dotansimha/graphql-yoga/issues/3315
=> fix: typescript module compat

packages/graphql-yoga/README.md
Way to boost GraphQL Conf. Discussed on [Slack](https://guild-oss.slack.com/archives/C03J3MBLJ6M/p1722873867810819).
=> add graphql conf 2024 banner

website/src/pages/docs/features/testing.mdx
example didn't work before, fixed it so it runs. Tested with Bun
=> Update testing.mdx, fix Mutation and Query Operations example

packages/graphql-yoga/README.md
Reverts dotansimha/graphql-yoga#3405
=> Remove graphql conf 2024 banner

.github/workflows/ci.yml, examples/apollo-managed-federation/package.json, examples/bun-yoga-ws/package.json
Instead of waiting for each other, use `fail-fast`
=> Ci improvements

.changeset/brave-cooks-shave.md, packages/graphql-yoga/src/server.ts
Any suggestions how this can be tested (if needs to be)?
ref: https://github.com/dotansimha/graphql-yoga/discussions/3758
=> fix: pass through `disposeOnProcessTerminate` to `createServerAdapter`

.changeset/neat-goats-see.md, examples/fastify/src/app.ts, jest.config.js, packages/graphql-yoga/package.json, packages/plugins/apollo-inline-trace/package.json, packages/plugins/apollo-managed-federation/package.json, packages/plugins/defer-stream/__tests__/defer-stream.spec.ts, packages/plugins/defer-stream/package.json, packages/plugins/jwt/src/plugin.ts, packages/subscription/package.json, pnpm-lock.yaml, website/src/content/docs/integrations/integration-with-fastify.mdx
Fastify supports WHATWG Response. So `Response` that Yoga returns can be passed directly in the Fastify route handler
=> Improve Fastify integration

website/src/app/layout.tsx
Updated the link to go to the Hive blog.
=> Link to Hive blog

.changeset/thirty-ears-obey.md, packages/graphql-yoga/package.json, packages/nestjs/package.json, packages/plugins/apollo-inline-trace/package.json, packages/plugins/apollo-managed-federation/package.json, packages/plugins/apollo-usage-report/package.json, packages/plugins/defer-stream/package.json, packages/subscription/package.json, pnpm-lock.yaml
In light of https://github.com/ardatan/whatwg-node/pull/2305.
=> Update whatwg-node packages

website/src/app/(landing-pages)/faq.mdx
=> chore(faq): fix typo in the faq

.changeset/@graphql-yoga_nestjs-federation-4088-dependencies.md, .changeset/@graphql-yoga_plugin-apollo-usage-report-4088-dependencies.md, .changeset/@graphql-yoga_plugin-response-cache-4088-dependencies.md, .changeset/graphql-yoga-4088-dependencies.md, .changeset/mean-garlics-refuse.md, .changeset/plain-eggs-win.md, .changeset/slimy-toys-fold.md, packages/graphql-yoga/package.json, packages/graphql-yoga/src/index.ts, packages/nestjs-federation/package.json, packages/plugins/apollo-inline-trace/package.json, packages/plugins/apollo-usage-report/package.json, packages/plugins/csrf-prevention/__tests__/csrf-prevention.spec.ts, packages/plugins/response-cache/package.json, pnpm-lock.yaml
- Update `@envelop/core`
- Fix Apollo Usage Report plugin `packag.json`
- Remove duplicated changeset
- Improve changeset of Apollo Usage Report
- Copy Envelop's Changeset for the new plugin util
=> feat(graphql-yoga): Add new `withState` plugin util

.changeset/metal-feet-wave.md, packages/graphql-yoga/src/graphiql.html
Fixes https://github.com/graphql-hive/graphql-yoga/issues/4183
=> fix(graphiql): load monaco workers properly in online mode
